import type {
  EquipmentState,
  FuelDefinition,
  GameState,
  GatherTarget,
  GatherTargetId,
  Machine,
  MachineId,
  ProcessRecipe,
  Quest,
  Recipe,
  ResourceId,
  Tool,
  ToolId,
} from './types'

export const resourceLabels: Record<ResourceId, string> = {
  log: 'Log',
  plank: 'Plank',
  stick: 'Stick',
  woodenAxe: 'Wooden Axe',
  woodenPickaxe: 'Wooden Pickaxe',
  stoneAxe: 'Stone Axe',
  stonePickaxe: 'Stone Pickaxe',
  ironAxe: 'Iron Axe',
  ironPickaxe: 'Iron Pickaxe',
  stoneHammer: 'Stone Hammer',
  ironHammer: 'Iron Hammer',
  stone: 'Stone',
  cobblestone: 'Cobblestone',
  gravel: 'Gravel',
  flint: 'Flint',
  ironOre: 'Iron Ore',
  copperOre: 'Copper Ore',
  tinOre: 'Tin Ore',
  crushedIronOre: 'Crushed Iron Ore',
  crushedCopperOre: 'Crushed Copper Ore',
  crushedTinOre: 'Crushed Tin Ore',
  coal: 'Coal',
  charcoal: 'Charcoal',
  mortar: 'Pestle & Mortar',
  ironIngot: 'Iron Ingot',
  copperIngot: 'Copper Ingot',
  tinIngot: 'Tin Ingot',
  ironDust: 'Iron Dust',
  copperDust: 'Copper Dust',
  tinDust: 'Tin Dust',
  bronzeIngot: 'Bronze Ingot',
  clay: 'Clay Lump',
  sand: 'Silica Sand',
  rubberSap: 'Sticky Sap',
  water: 'Water',
  copperPlate: 'Copper Plate',
  tinPlate: 'Tin Plate',
  copperWire: 'Drawn Copper Wire',
  bronzeBlend: 'Bronze Dust',
  firebrick: 'Firebrick',
  steamCasing: 'Riveted Steam Casing',
  basicBoard: 'Pressed Board',
  conductiveWire: 'Insulated Wire',
  primitiveCircuit: 'Clicker Circuit',
}

export const tools: Record<ToolId, Tool> = {
  bareHand: {
    id: 'bareHand',
    name: 'Bare Hand',
    description: 'Slow, stubborn, and good enough for the first tree.',
    damageByTarget: { tree: 1 },
  },
  woodenAxe: {
    id: 'woodenAxe',
    name: 'Wooden Axe',
    description: 'A crude edge that makes trees stop arguing so much.',
    damageByTarget: { tree: 3 },
  },
  woodenPickaxe: {
    id: 'woodenPickaxe',
    name: 'Wooden Pickaxe',
    description: 'A blocky starter pick that can crack soft stone.',
    damageByTarget: { stone: 2 },
  },
  stoneAxe: {
    id: 'stoneAxe',
    name: 'Stone Axe',
    description: 'A heavier chopping head that bites deeper than wood.',
    damageByTarget: { tree: 5 },
  },
  stonePickaxe: {
    id: 'stonePickaxe',
    name: 'Stone Pickaxe',
    description: 'A stronger pick head that chips stone and rough iron.',
    damageByTarget: { stone: 4, gravelPatch: 3, ironVein: 4 },
  },
  ironAxe: {
    id: 'ironAxe',
    name: 'Iron Axe',
    description: 'A proper metal axe that makes tree work quick.',
    damageByTarget: { tree: 8 },
  },
  ironPickaxe: {
    id: 'ironPickaxe',
    name: 'Iron Pickaxe',
    description: 'A strong pick for copper, tin, coal, and faster stone.',
    damageByTarget: { stone: 7, gravelPatch: 6, ironVein: 7, copperVein: 6, tinVein: 6, coalSeam: 6 },
  },
}

export const gatherTargets: Record<GatherTargetId, GatherTarget> = {
  tree: {
    id: 'tree',
    name: 'Tree',
    description: 'Damage the trunk until a log breaks free.',
    maxHp: 12,
    drops: [{ id: 'log', amount: 1 }],
    preferredTool: 'woodenAxe',
  },
  stone: {
    id: 'stone',
    name: 'Stone',
    description: 'Hard rock that needs a pickaxe before it gives up cobblestone.',
    maxHp: 24,
    drops: [{ id: 'cobblestone', amount: 1 }],
    preferredTool: 'woodenPickaxe',
  },
  gravelPatch: {
    id: 'gravelPatch',
    name: 'Gravel Patch',
    description: 'Loose rough gravel with useful flint hidden inside.',
    maxHp: 30,
    drops: [{ id: 'gravel', amount: 1 }],
    preferredTool: 'stonePickaxe',
  },
  copperVein: {
    id: 'copperVein',
    name: 'Copper Vein',
    description: 'Soft orange ore that needs an iron pickaxe before it breaks loose.',
    maxHp: 48,
    drops: [{ id: 'copperOre', amount: 1 }],
    preferredTool: 'ironPickaxe',
  },
  ironVein: {
    id: 'ironVein',
    name: 'Iron Vein',
    description: 'Dark ore that bridges stone tools into better metal tools.',
    maxHp: 40,
    drops: [{ id: 'ironOre', amount: 1 }],
    preferredTool: 'stonePickaxe',
  },
  tinVein: {
    id: 'tinVein',
    name: 'Tin Vein',
    description: 'Pale flecks in stubborn stone. Slow, but vital for bronze.',
    maxHp: 56,
    drops: [{ id: 'tinOre', amount: 1 }],
    preferredTool: 'ironPickaxe',
  },
  coalSeam: {
    id: 'coalSeam',
    name: 'Coal Seam',
    description: 'Dense black fuel. Useful, but painfully slow to dig out early.',
    maxHp: 120,
    drops: [{ id: 'coal', amount: 1 }],
    preferredTool: 'ironPickaxe',
  },
}

export const machines: Record<MachineId, Machine> = {
  furnace: {
    id: 'furnace',
    name: 'Primitive Furnace',
    description: 'A simple fuel-fed furnace for slow ore smelting.',
    tier: 'manual',
  },
}

export const recipes: Recipe[] = [
  {
    id: 'craft_planks',
    name: 'Split Log into Planks',
    description: 'Break one log into simple boards.',
    tier: 'manual',
    durationMs: 900,
    inputs: [{ id: 'log', amount: 1 }],
    outputs: [{ id: 'plank', amount: 4 }],
    unlockedBy: 'punchTree',
  },
  {
    id: 'craft_sticks',
    name: 'Carve Sticks',
    description: 'Thin planks into handles for early tools.',
    tier: 'manual',
    durationMs: 800,
    inputs: [{ id: 'plank', amount: 2 }],
    outputs: [{ id: 'stick', amount: 4 }],
    unlockedBy: 'craftPlanks',
  },
  {
    id: 'craft_wooden_axe',
    name: 'Craft Wooden Axe',
    description: 'A first table-made tool. Not fancy, but the tree will notice.',
    tier: 'manual',
    durationMs: 1400,
    inputs: [
      { id: 'plank', amount: 3 },
      { id: 'stick', amount: 2 },
    ],
    pattern: ['plank', 'plank', null, 'plank', 'stick', null, null, 'stick', null],
    outputs: [{ id: 'woodenAxe', amount: 1 }],
    unlockedBy: 'craftSticks',
  },
  {
    id: 'craft_wooden_pickaxe',
    name: 'Craft Wooden Pickaxe',
    description: 'A starter pick for cracking stone into cobblestone.',
    tier: 'manual',
    durationMs: 1400,
    inputs: [
      { id: 'plank', amount: 3 },
      { id: 'stick', amount: 2 },
    ],
    pattern: ['plank', 'plank', 'plank', null, 'stick', null, null, 'stick', null],
    outputs: [{ id: 'woodenPickaxe', amount: 1 }],
    unlockedBy: 'craftSticks',
  },
  {
    id: 'craft_stone_axe',
    name: 'Craft Stone Axe',
    description: 'A cobblestone axe head on a simple stick handle.',
    tier: 'manual',
    durationMs: 1600,
    inputs: [
      { id: 'cobblestone', amount: 3 },
      { id: 'stick', amount: 2 },
    ],
    pattern: ['cobblestone', 'cobblestone', null, 'cobblestone', 'stick', null, null, 'stick', null],
    outputs: [{ id: 'stoneAxe', amount: 1 }],
    unlockedBy: 'craftSticks',
  },
  {
    id: 'craft_stone_pickaxe',
    name: 'Craft Stone Pickaxe',
    description: 'Cobblestone across the top with a pair of sturdy handles.',
    tier: 'manual',
    durationMs: 1600,
    inputs: [
      { id: 'cobblestone', amount: 3 },
      { id: 'stick', amount: 2 },
    ],
    pattern: ['cobblestone', 'cobblestone', 'cobblestone', null, 'stick', null, null, 'stick', null],
    outputs: [{ id: 'stonePickaxe', amount: 1 }],
    unlockedBy: 'craftSticks',
  },
  {
    id: 'craft_iron_axe',
    name: 'Craft Iron Axe',
    description: 'An iron axe head on a familiar stick handle.',
    tier: 'manual',
    durationMs: 1800,
    inputs: [
      { id: 'ironIngot', amount: 3 },
      { id: 'stick', amount: 2 },
    ],
    pattern: ['ironIngot', 'ironIngot', null, 'ironIngot', 'stick', null, null, 'stick', null],
    outputs: [{ id: 'ironAxe', amount: 1 }],
    unlockedBy: 'firstDirt',
  },
  {
    id: 'craft_iron_pickaxe',
    name: 'Craft Iron Pickaxe',
    description: 'Iron across the top for the first serious mining step.',
    tier: 'manual',
    durationMs: 1800,
    inputs: [
      { id: 'ironIngot', amount: 3 },
      { id: 'stick', amount: 2 },
    ],
    pattern: ['ironIngot', 'ironIngot', 'ironIngot', null, 'stick', null, null, 'stick', null],
    outputs: [{ id: 'ironPickaxe', amount: 1 }],
    unlockedBy: 'firstDirt',
  },
  {
    id: 'knap_flint',
    name: 'Knap Flint',
    description: 'Pick through gravel until a sharp flint piece turns up.',
    tier: 'manual',
    durationMs: 900,
    inputs: [{ id: 'gravel', amount: 2 }],
    outputs: [{ id: 'flint', amount: 1 }],
    unlockedBy: 'firstDirt',
  },
  {
    id: 'craft_stone_hammer',
    name: 'Craft Stone Hammer',
    description: 'A crude hammer for breaking ore into better furnace feed.',
    tier: 'manual',
    durationMs: 1600,
    inputs: [
      { id: 'cobblestone', amount: 6 },
      { id: 'stick', amount: 1 },
    ],
    pattern: ['cobblestone', 'cobblestone', null, 'cobblestone', 'cobblestone', 'stick', 'cobblestone', 'cobblestone', null],
    outputs: [{ id: 'stoneHammer', amount: 1 }],
    unlockedBy: 'craftSticks',
  },
  {
    id: 'craft_iron_hammer',
    name: 'Craft Iron Hammer',
    description: 'A heavier hammer that lasts much longer than stone.',
    tier: 'manual',
    durationMs: 1800,
    inputs: [
      { id: 'ironIngot', amount: 6 },
      { id: 'stick', amount: 1 },
    ],
    pattern: ['ironIngot', 'ironIngot', null, 'ironIngot', 'ironIngot', 'stick', 'ironIngot', 'ironIngot', null],
    outputs: [{ id: 'ironHammer', amount: 1 }],
    unlockedBy: 'firstDirt',
  },
  {
    id: 'crush_iron_ore',
    name: 'Crush Iron Ore',
    description: 'Hammer iron ore into a richer furnace feed.',
    tier: 'manual',
    durationMs: 1800,
    inputs: [{ id: 'ironOre', amount: 1 }],
    catalysts: [{ id: 'stoneHammer', amount: 1 }],
    durabilityCosts: [{ id: 'stoneHammer', amount: 1 }],
    pattern: [null, 'stoneHammer', null, null, 'ironOre', null, null, null, null],
    outputs: [{ id: 'crushedIronOre', amount: 1 }],
    unlockedBy: 'firstDirt',
  },
  {
    id: 'crush_copper_ore',
    name: 'Crush Copper Ore',
    description: 'Hammer copper ore into a richer furnace feed.',
    tier: 'bronze',
    durationMs: 1800,
    inputs: [{ id: 'copperOre', amount: 1 }],
    catalysts: [{ id: 'stoneHammer', amount: 1 }],
    durabilityCosts: [{ id: 'stoneHammer', amount: 1 }],
    pattern: [null, 'stoneHammer', null, null, 'copperOre', null, null, null, null],
    outputs: [{ id: 'crushedCopperOre', amount: 1 }],
    unlockedBy: 'copperAndTin',
  },
  {
    id: 'crush_tin_ore',
    name: 'Crush Tin Ore',
    description: 'Hammer tin ore into a richer furnace feed.',
    tier: 'bronze',
    durationMs: 1800,
    inputs: [{ id: 'tinOre', amount: 1 }],
    catalysts: [{ id: 'stoneHammer', amount: 1 }],
    durabilityCosts: [{ id: 'stoneHammer', amount: 1 }],
    pattern: [null, 'stoneHammer', null, null, 'tinOre', null, null, null, null],
    outputs: [{ id: 'crushedTinOre', amount: 1 }],
    unlockedBy: 'copperAndTin',
  },
  {
    id: 'craft_mortar',
    name: 'Craft Pestle & Mortar',
    description: 'A rough stone cup and pestle for grinding early ingots into dust.',
    tier: 'manual',
    durationMs: 1400,
    inputs: [
      { id: 'cobblestone', amount: 3 },
      { id: 'stick', amount: 1 },
    ],
    outputs: [{ id: 'mortar', amount: 1 }],
    unlockedBy: 'craftSticks',
  },
  {
    id: 'build_furnace',
    name: 'Build Primitive Furnace',
    description: 'Eight cobblestone make a fuel-fed box for slow ore smelting.',
    tier: 'manual',
    durationMs: 5000,
    inputs: [{ id: 'cobblestone', amount: 8 }],
    outputs: [],
    machineOutputs: [{ id: 'furnace', amount: 1 }],
    unlockedBy: 'firstDirt',
  },
  {
    id: 'firebrick',
    name: 'Bake Firebrick',
    description: 'Heat-hardened brick for primitive pressure vessels.',
    tier: 'bronze',
    durationMs: 4500,
    inputs: [
      { id: 'clay', amount: 2 },
      { id: 'sand', amount: 1 },
      { id: 'coal', amount: 1 },
    ],
    outputs: [{ id: 'firebrick', amount: 2 }],
    requiredMachine: 'furnace',
    unlockedBy: 'copperAndTin',
  },
  {
    id: 'bronze_blend',
    name: 'Mix Bronze Dust',
    description: 'Three copper dust and one tin dust make the first bronze batch.',
    tier: 'bronze',
    durationMs: 3500,
    inputs: [
      { id: 'copperDust', amount: 3 },
      { id: 'tinDust', amount: 1 },
    ],
    outputs: [{ id: 'bronzeBlend', amount: 4 }],
    unlockedBy: 'copperAndTin',
  },
  {
    id: 'grind_iron_ingot',
    name: 'Grind Iron Dust',
    description: 'Use the pestle and mortar to break an iron ingot into dust.',
    tier: 'manual',
    durationMs: 1600,
    inputs: [{ id: 'ironIngot', amount: 1 }],
    catalysts: [{ id: 'mortar', amount: 1 }],
    durabilityCosts: [{ id: 'mortar', amount: 1 }],
    pattern: [null, 'mortar', null, null, 'ironIngot', null, null, null, null],
    outputs: [{ id: 'ironDust', amount: 1 }],
    unlockedBy: 'firstDirt',
  },
  {
    id: 'grind_copper_ingot',
    name: 'Grind Copper Dust',
    description: 'Use the pestle and mortar to break a copper ingot into dust.',
    tier: 'bronze',
    durationMs: 1600,
    inputs: [{ id: 'copperIngot', amount: 1 }],
    catalysts: [{ id: 'mortar', amount: 1 }],
    durabilityCosts: [{ id: 'mortar', amount: 1 }],
    pattern: [null, 'mortar', null, null, 'copperIngot', null, null, null, null],
    outputs: [{ id: 'copperDust', amount: 1 }],
    unlockedBy: 'copperAndTin',
  },
  {
    id: 'grind_tin_ingot',
    name: 'Grind Tin Dust',
    description: 'Use the pestle and mortar to break a tin ingot into dust.',
    tier: 'bronze',
    durationMs: 1600,
    inputs: [{ id: 'tinIngot', amount: 1 }],
    catalysts: [{ id: 'mortar', amount: 1 }],
    durabilityCosts: [{ id: 'mortar', amount: 1 }],
    pattern: [null, 'mortar', null, null, 'tinIngot', null, null, null, null],
    outputs: [{ id: 'tinDust', amount: 1 }],
    unlockedBy: 'copperAndTin',
  },
  {
    id: 'copper_plate',
    name: 'Hand-Hammer Copper Plate',
    description: 'Flatten copper into a useful plate. Your wrist will remember this.',
    tier: 'bronze',
    durationMs: 5500,
    inputs: [{ id: 'copperOre', amount: 2 }],
    outputs: [{ id: 'copperPlate', amount: 1 }],
    unlockedBy: 'copperAndTin',
  },
  {
    id: 'tin_plate',
    name: 'Hand-Hammer Tin Plate',
    description: 'Soft tin sheets for early electrical tricks.',
    tier: 'bronze',
    durationMs: 4500,
    inputs: [{ id: 'tinOre', amount: 2 }],
    outputs: [{ id: 'tinPlate', amount: 1 }],
    unlockedBy: 'copperAndTin',
  },
  {
    id: 'copper_wire',
    name: 'Hand-Draw Copper Wire',
    description: 'Pull copper plate into rough wire.',
    tier: 'bronze',
    durationMs: 4000,
    inputs: [{ id: 'copperPlate', amount: 1 }],
    outputs: [{ id: 'copperWire', amount: 2 }],
    unlockedBy: 'copperAndTin',
  },
]

export const fuelDefinitions: Record<string, FuelDefinition> = {
  stick: { id: 'stick', burnMs: 1200 },
  plank: { id: 'plank', burnMs: 3200 },
  log: { id: 'log', burnMs: 10000 },
  charcoal: { id: 'charcoal', burnMs: 30000 },
  coal: { id: 'coal', burnMs: 80000 },
}

export const processRecipes: ProcessRecipe[] = [
  {
    id: 'charcoal_from_log',
    name: 'Charcoal From Log',
    description: 'Bake logs into a cleaner early fuel.',
    tier: 'manual',
    machineId: 'furnace',
    durationMs: 10000,
    input: { id: 'log', amount: 1 },
    output: { id: 'charcoal', amount: 1 },
  },
  {
    id: 'smelt_iron_ingot',
    name: 'Smelt Iron Ingot',
    description: 'Slowly smelt iron ore into a tool-ready ingot.',
    tier: 'bronze',
    machineId: 'furnace',
    durationMs: 14000,
    input: { id: 'ironOre', amount: 1 },
    output: { id: 'ironIngot', amount: 1 },
  },
  {
    id: 'smelt_crushed_iron_ingot',
    name: 'Smelt Crushed Iron',
    description: 'Smelt crushed iron ore for a better ingot yield.',
    tier: 'bronze',
    machineId: 'furnace',
    durationMs: 14000,
    input: { id: 'crushedIronOre', amount: 1 },
    output: { id: 'ironIngot', amount: 2 },
  },
  {
    id: 'smelt_copper_ingot',
    name: 'Smelt Copper Ingot',
    description: 'Slowly smelt copper ore into a usable ingot.',
    tier: 'bronze',
    machineId: 'furnace',
    durationMs: 12000,
    input: { id: 'copperOre', amount: 1 },
    output: { id: 'copperIngot', amount: 1 },
  },
  {
    id: 'smelt_crushed_copper_ingot',
    name: 'Smelt Crushed Copper',
    description: 'Smelt crushed copper ore for a better ingot yield.',
    tier: 'bronze',
    machineId: 'furnace',
    durationMs: 12000,
    input: { id: 'crushedCopperOre', amount: 1 },
    output: { id: 'copperIngot', amount: 2 },
  },
  {
    id: 'smelt_tin_ingot',
    name: 'Smelt Tin Ingot',
    description: 'Slowly smelt tin ore into a usable ingot.',
    tier: 'bronze',
    machineId: 'furnace',
    durationMs: 12000,
    input: { id: 'tinOre', amount: 1 },
    output: { id: 'tinIngot', amount: 1 },
  },
  {
    id: 'smelt_crushed_tin_ingot',
    name: 'Smelt Crushed Tin',
    description: 'Smelt crushed tin ore for a better ingot yield.',
    tier: 'bronze',
    machineId: 'furnace',
    durationMs: 12000,
    input: { id: 'crushedTinOre', amount: 1 },
    output: { id: 'tinIngot', amount: 2 },
  },
  {
    id: 'smelt_bronze_ingot',
    name: 'Smelt Bronze Ingot',
    description: 'Fire bronze dust into a first proper bronze ingot.',
    tier: 'bronze',
    machineId: 'furnace',
    durationMs: 14000,
    input: { id: 'bronzeBlend', amount: 1 },
    output: { id: 'bronzeIngot', amount: 1 },
  },
]

export const quests: Quest[] = [
  {
    id: 'punchTree',
    chapter: 'First Tree',
    title: 'Punch a log loose',
    description: 'Damage the tree until one full log drops into your inventory.',
    requirements: {
      resources: [{ id: 'log', amount: 1 }],
    },
    rewards: {
      unlocks: ['craftPlanks'],
    },
  },
  {
    id: 'craftPlanks',
    chapter: 'First Tree',
    title: 'Split logs into planks',
    description: 'Turn rough logs into useful boards.',
    requirements: {
      resources: [{ id: 'plank', amount: 4 }],
    },
    rewards: {
      unlocks: ['craftSticks'],
    },
  },
  {
    id: 'craftSticks',
    chapter: 'First Tool',
    title: 'Carve sticks',
    description: 'Tools need handles before they can become helpful.',
    requirements: {
      resources: [{ id: 'stick', amount: 4 }],
    },
    rewards: {
      unlocks: ['craftAxe', 'firstDirt'],
    },
  },
  {
    id: 'craftAxe',
    chapter: 'First Tool',
    title: 'Make a wooden axe',
    description: 'Three planks and two sticks become your first speed upgrade.',
    requirements: {
      resources: [{ id: 'woodenAxe', amount: 1 }],
    },
    rewards: {
      unlocks: ['chopFaster'],
    },
  },
  {
    id: 'chopFaster',
    chapter: 'First Tool',
    title: 'Chop with the axe',
    description: 'Use the wooden axe to break a second log faster.',
    requirements: {
      resources: [{ id: 'log', amount: 2 }],
    },
    rewards: {
      resources: [{ id: 'plank', amount: 2 }],
    },
  },
  {
    id: 'firstDirt',
    chapter: 'Iron Before Bronze',
    title: 'Forge an iron pickaxe',
    description: 'Stone tools open iron. Smelt it, then make the pick that can bite into copper and tin.',
    requirements: {
      resources: [{ id: 'ironPickaxe', amount: 1 }],
      machines: [{ id: 'furnace', amount: 1 }],
    },
    rewards: {
      resources: [{ id: 'clay', amount: 4 }],
      unlocks: ['copperAndTin'],
    },
  },
  {
    id: 'copperAndTin',
    chapter: 'Copper and Tin',
    title: 'Find the soft metals',
    description: 'Copper and tin unlock the first real progression knot.',
    requirements: {
      resources: [
        { id: 'copperOre', amount: 12 },
        { id: 'tinOre', amount: 6 },
      ],
    },
    rewards: {
      resources: [{ id: 'sand', amount: 6 }],
      unlocks: ['bronzeAge'],
    },
  },
  {
    id: 'bronzeAge',
    chapter: 'Bronze Age',
    title: 'Mix the first bronze dust',
    description: 'Grind copper and tin, then mix them into the first bronze batch.',
    requirements: {
      resources: [{ id: 'bronzeBlend', amount: 4 }],
      machines: [{ id: 'furnace', amount: 1 }],
    },
    rewards: {
      resources: [{ id: 'copperOre', amount: 6 }],
    },
  },
]

export const initialResources: Record<ResourceId, number> = Object.keys(resourceLabels).reduce(
  (resources, id) => ({ ...resources, [id]: 0 }),
  {} as Record<ResourceId, number>,
)

export const initialMachines: Record<MachineId, number> = Object.keys(machines).reduce(
  (builtMachines, id) => ({ ...builtMachines, [id]: 0 }),
  {} as Record<MachineId, number>,
)

export const initialEquipment: EquipmentState = {
  helmet: null,
  chestplate: null,
  leggings: null,
  boots: null,
  axe: null,
  shovel: null,
  pickaxe: null,
  weapon: null,
}

export function createInitialState(now = Date.now()): GameState {
  return {
    version: 1,
    resources: { ...initialResources },
    machines: { ...initialMachines },
    machineInstances: [],
    completedQuests: [],
    unlockedQuests: ['punchTree'],
    craftedResources: [],
    equipment: { ...initialEquipment },
    durability: {},
    gatherProgress: {},
    machineProgress: {},
    lastSavedAt: now,
  }
}
