import type {
  EquipmentState,
  FuelDefinition,
  GameState,
  GatherTarget,
  GatherTargetId,
  Machine,
  MachineId,
  ProcessRecipe,
  Quest,
  QuestChapter,
  Recipe,
  ResourceId,
  Tool,
  ToolId,
} from './types'

export const resourceLabels: Record<ResourceId, string> = {
  log: 'Log',
  plank: 'Plank',
  stick: 'Stick',
  treeTap: 'Tree Tap',
  woodenAxe: 'Wooden Axe',
  woodenPickaxe: 'Wooden Pickaxe',
  woodenShovel: 'Wooden Shovel',
  stoneAxe: 'Stone Axe',
  stonePickaxe: 'Stone Pickaxe',
  stoneShovel: 'Stone Shovel',
  ironAxe: 'Iron Axe',
  ironPickaxe: 'Iron Pickaxe',
  ironShovel: 'Iron Shovel',
  stoneHammer: 'Stone Hammer',
  ironHammer: 'Iron Hammer',
  ironFile: 'Iron File',
  bronzeFile: 'Bronze File',
  ironWrench: 'Iron Wrench',
  bronzeWrench: 'Bronze Wrench',
  stone: 'Stone',
  cobblestone: 'Cobblestone',
  gravel: 'Gravel',
  flint: 'Flint',
  ironOre: 'Iron Ore',
  copperOre: 'Copper Ore',
  tinOre: 'Tin Ore',
  redstoneDust: 'Redstone Dust',
  crushedIronOre: 'Crushed Iron Ore',
  crushedCopperOre: 'Crushed Copper Ore',
  crushedTinOre: 'Crushed Tin Ore',
  coal: 'Coal',
  charcoal: 'Charcoal',
  coalCoke: 'Coal Coke',
  mortar: 'Pestle & Mortar',
  ironMortar: 'Iron Pestle & Mortar',
  bronzeMortar: 'Bronze Pestle & Mortar',
  unfiredBrick: 'Unfired Brick',
  brick: 'Brick',
  bucket: 'Bucket',
  ironIngot: 'Iron Ingot',
  copperIngot: 'Copper Ingot',
  tinIngot: 'Tin Ingot',
  ironDust: 'Iron Dust',
  copperDust: 'Copper Dust',
  tinDust: 'Tin Dust',
  bronzeIngot: 'Bronze Ingot',
  clay: 'Clay Lump',
  sand: 'Silica Sand',
  rubberSap: 'Sticky Resin',
  pipeSealant: 'Pipe Sealant',
  rubber: 'Rubber',
  water: 'Water',
  ironPlate: 'Iron Plate',
  copperPlate: 'Copper Plate',
  tinPlate: 'Tin Plate',
  bronzePlate: 'Bronze Plate',
  ironRod: 'Iron Rod',
  copperRod: 'Copper Rod',
  tinRod: 'Tin Rod',
  bronzeRod: 'Bronze Rod',
  steelIngot: 'Steel Ingot',
  steelPlate: 'Steel Plate',
  steelRod: 'Steel Rod',
  copperWire: 'Drawn Copper Wire',
  glass: 'Glass',
  glassTube: 'Glass Tube',
  woodPulp: 'Wood Pulp',
  carbonDust: 'Carbon Dust',
  redAlloyIngot: 'Red Alloy Ingot',
  redAlloyWire: 'Red Alloy Wire',
  resistor: 'Resistor',
  vacuumTube: 'Vacuum Tube',
  bronzeBlend: 'Bronze Dust',
  steamCasing: 'Riveted Steam Casing',
  cokeOvenBrick: 'Coke Oven Brick',
  firebrick: 'Firebrick',
  bbfCasing: 'BBF Casing',
  basicBoard: 'Coated Circuit Board',
  conductiveWire: 'Insulated Copper Wire',
  primitiveCircuit: 'Basic Electronic Circuit',
}

export const tools: Record<ToolId, Tool> = {
  bareHand: {
    id: 'bareHand',
    name: 'Bare Hand',
    description: 'Slow, stubborn, and good enough for the first tree.',
    damageByTarget: { tree: 1 },
  },
  woodenAxe: {
    id: 'woodenAxe',
    name: 'Wooden Axe',
    description: 'A crude edge that makes trees stop arguing so much.',
    damageByTarget: { tree: 3 },
  },
  woodenPickaxe: {
    id: 'woodenPickaxe',
    name: 'Wooden Pickaxe',
    description: 'A blocky starter pick that can crack soft stone.',
    damageByTarget: { stone: 2 },
  },
  woodenShovel: {
    id: 'woodenShovel',
    name: 'Wooden Shovel',
    description: 'A flat board on a handle for slow clay digging.',
    damageByTarget: { clayPatch: 3, sandPatch: 3, gravelPatch: 2 },
  },
  treeTap: {
    id: 'treeTap',
    name: 'Tree Tap',
    description: 'A small wooden spile for drawing sticky resin from rubber trees.',
    damageByTarget: { rubberTree: 4 },
  },
  stoneAxe: {
    id: 'stoneAxe',
    name: 'Stone Axe',
    description: 'A heavier chopping head that bites deeper than wood.',
    damageByTarget: { tree: 5 },
  },
  stonePickaxe: {
    id: 'stonePickaxe',
    name: 'Stone Pickaxe',
    description: 'A stronger pick head that chips stone and rough iron.',
    damageByTarget: { stone: 4, ironVein: 4 },
  },
  stoneShovel: {
    id: 'stoneShovel',
    name: 'Stone Shovel',
    description: 'A flat cobblestone blade for digging soft clay.',
    damageByTarget: { clayPatch: 5, sandPatch: 5, gravelPatch: 4 },
  },
  ironAxe: {
    id: 'ironAxe',
    name: 'Iron Axe',
    description: 'A proper metal axe that makes tree work quick.',
    damageByTarget: { tree: 8 },
  },
  ironPickaxe: {
    id: 'ironPickaxe',
    name: 'Iron Pickaxe',
    description: 'A strong pick for copper, tin, coal, and faster stone.',
    damageByTarget: { stone: 7, ironVein: 7, copperVein: 6, tinVein: 6, redstoneVein: 5, coalSeam: 6 },
  },
  ironShovel: {
    id: 'ironShovel',
    name: 'Iron Shovel',
    description: 'A proper metal shovel that makes clay work quick.',
    damageByTarget: { clayPatch: 8, sandPatch: 8, gravelPatch: 7 },
  },
}

export const gatherTargets: Record<GatherTargetId, GatherTarget> = {
  tree: {
    id: 'tree',
    name: 'Tree',
    description: 'Damage the trunk until a log breaks free.',
    maxHp: 12,
    drops: [{ id: 'log', amount: 1 }],
    preferredTool: 'woodenAxe',
  },
  rubberTree: {
    id: 'rubberTree',
    name: 'Rubber Tree',
    description: 'A resin-rich tree that needs a tap before the sticky sap flows.',
    maxHp: 28,
    drops: [{ id: 'rubberSap', amount: 1 }],
    preferredTool: 'treeTap',
  },
  stone: {
    id: 'stone',
    name: 'Stone',
    description: 'Hard rock that needs a pickaxe before it gives up cobblestone.',
    maxHp: 24,
    drops: [{ id: 'cobblestone', amount: 1 }],
    preferredTool: 'woodenPickaxe',
  },
  gravelPatch: {
    id: 'gravelPatch',
    name: 'Gravel Patch',
    description: 'Loose wet gravel with useful flint hidden inside.',
    maxHp: 30,
    drops: [{ id: 'gravel', amount: 1 }],
    preferredTool: 'woodenShovel',
  },
  clayPatch: {
    id: 'clayPatch',
    name: 'Clay Patch',
    description: 'Wet clay beside still water. A shovel lifts workable lumps.',
    maxHp: 35,
    drops: [{ id: 'clay', amount: 1 }],
    preferredTool: 'stoneShovel',
  },
  sandPatch: {
    id: 'sandPatch',
    name: 'Sand Bank',
    description: 'Pale silica sand at the lake edge. A shovel gathers clean handfuls.',
    maxHp: 24,
    drops: [{ id: 'sand', amount: 1 }],
    preferredTool: 'woodenShovel',
  },
  copperVein: {
    id: 'copperVein',
    name: 'Copper Vein',
    description: 'Soft orange ore that needs an iron pickaxe before it breaks loose.',
    maxHp: 48,
    drops: [{ id: 'copperOre', amount: 1 }],
    preferredTool: 'ironPickaxe',
  },
  ironVein: {
    id: 'ironVein',
    name: 'Iron Vein',
    description: 'Dark ore that bridges stone tools into better metal tools.',
    maxHp: 40,
    drops: [{ id: 'ironOre', amount: 1 }],
    preferredTool: 'stonePickaxe',
  },
  tinVein: {
    id: 'tinVein',
    name: 'Tin Vein',
    description: 'Pale flecks in stubborn stone. Slow, but vital for bronze.',
    maxHp: 56,
    drops: [{ id: 'tinOre', amount: 1 }],
    preferredTool: 'ironPickaxe',
  },
  redstoneVein: {
    id: 'redstoneVein',
    name: 'Redstone Vein',
    description: 'Glowing red dust trapped in hard stone. Iron tools are the first bite point.',
    maxHp: 72,
    drops: [{ id: 'redstoneDust', amount: 1 }],
    preferredTool: 'ironPickaxe',
  },
  coalSeam: {
    id: 'coalSeam',
    name: 'Coal Seam',
    description: 'Dense black fuel. Useful, but painfully slow to dig out early.',
    maxHp: 120,
    drops: [{ id: 'coal', amount: 1 }],
    preferredTool: 'ironPickaxe',
  },
}

export const machines: Record<MachineId, Machine> = {
  furnace: {
    id: 'furnace',
    name: 'Primitive Furnace',
    description: 'A simple fuel-fed furnace for slow ore smelting.',
    tier: 'manual',
  },
  well: {
    id: 'well',
    name: 'Well',
    description: 'A brick-lined water source that can keep four adjacent boilers supplied.',
    tier: 'steam',
  },
  steamBoiler: {
    id: 'steamBoiler',
    name: 'Steam Boiler',
    description: 'Burns fuel with adjacent well water to build a local steam reserve.',
    tier: 'steam',
  },
  steamTank: {
    id: 'steamTank',
    name: 'Iron Steam Tank',
    description: 'Stores steam from nearby boilers so machines can draw from a local reserve.',
    tier: 'steam',
  },
  copperPipe: {
    id: 'copperPipe',
    name: 'Copper Steam Pipe',
    description: 'A narrow early pipe that moves steam slowly through the factory floor.',
    tier: 'steam',
  },
  bronzePipe: {
    id: 'bronzePipe',
    name: 'Bronze Steam Pipe',
    description: 'A sturdier pipe with better steam throughput for busier layouts.',
    tier: 'steam',
  },
  ironPipe: {
    id: 'ironPipe',
    name: 'Iron Steam Pipe',
    description: 'A wide pipe that moves steam quickly through compact machine rooms.',
    tier: 'steam',
  },
  steamMacerator: {
    id: 'steamMacerator',
    name: 'Steam Macerator',
    description: 'Uses boiler steam to crush ores and grind dusts automatically.',
    tier: 'steam',
  },
  steamForgeHammer: {
    id: 'steamForgeHammer',
    name: 'Steam Forge Hammer',
    description: 'Uses steam power to hammer ingots into plates without hand tooling.',
    tier: 'steam',
  },
  steamCompressor: {
    id: 'steamCompressor',
    name: 'Steam Compressor',
    description: 'Compresses ceramic and metal parts for sturdier steam-era builds.',
    tier: 'steam',
  },
  steamExtractor: {
    id: 'steamExtractor',
    name: 'Steam Extractor',
    description: 'Pulls useful materials from sticky resin and other soft feedstock.',
    tier: 'steam',
  },
  steamAlloySmelter: {
    id: 'steamAlloySmelter',
    name: 'Steam Alloy Smelter',
    description: 'Automates early alloy firing with a steady steam draw.',
    tier: 'steam',
  },
  steamFurnace: {
    id: 'steamFurnace',
    name: 'Steam Furnace',
    description: 'A faster steam-fed furnace for ore and dust smelting.',
    tier: 'steam',
  },
  cokeOven: {
    id: 'cokeOven',
    name: 'Coke Oven',
    description: 'Slowly bakes wood and coal into better fuel while collecting creosote.',
    tier: 'steam',
  },
  brickedBlastFurnacePart: {
    id: 'brickedBlastFurnacePart',
    name: 'BBF Casing',
    description: 'One dense firebrick casing block. Place four in a 2x2 to form a Bricked Blast Furnace.',
    tier: 'steam',
  },
  brickedBlastFurnace: {
    id: 'brickedBlastFurnace',
    name: 'Bricked Blast Furnace',
    description: 'A slow firebrick stack for the first steel batches.',
    tier: 'steam',
  },
}

export const recipes: Recipe[] = [
  {
    id: 'craft_planks',
    name: 'Split Log into Planks',
    description: 'Break one log into simple boards.',
    tier: 'manual',
    durationMs: 900,
    inputs: [{ id: 'log', amount: 1 }],
    outputs: [{ id: 'plank', amount: 4 }],
    unlockedBy: 'punchTree',
  },
  {
    id: 'craft_sticks',
    name: 'Carve Sticks',
    description: 'Thin planks into handles for early tools.',
    tier: 'manual',
    durationMs: 800,
    inputs: [{ id: 'plank', amount: 2 }],
    outputs: [{ id: 'stick', amount: 4 }],
    unlockedBy: 'craftPlanks',
  },
  {
    id: 'craft_wooden_axe',
    name: 'Craft Wooden Axe',
    description: 'A first table-made tool. Not fancy, but the tree will notice.',
    tier: 'manual',
    durationMs: 1400,
    inputs: [
      { id: 'plank', amount: 3 },
      { id: 'stick', amount: 2 },
    ],
    pattern: ['plank', 'plank', null, 'plank', 'stick', null, null, 'stick', null],
    outputs: [{ id: 'woodenAxe', amount: 1 }],
    unlockedBy: 'craftSticks',
  },
  {
    id: 'craft_wooden_pickaxe',
    name: 'Craft Wooden Pickaxe',
    description: 'A starter pick for cracking stone into cobblestone.',
    tier: 'manual',
    durationMs: 1400,
    inputs: [
      { id: 'plank', amount: 3 },
      { id: 'stick', amount: 2 },
    ],
    pattern: ['plank', 'plank', 'plank', null, 'stick', null, null, 'stick', null],
    outputs: [{ id: 'woodenPickaxe', amount: 1 }],
    unlockedBy: 'craftSticks',
  },
  {
    id: 'craft_wooden_shovel',
    name: 'Craft Wooden Shovel',
    description: 'A plank shovel head on a pair of simple handles.',
    tier: 'manual',
    durationMs: 1200,
    inputs: [
      { id: 'plank', amount: 1 },
      { id: 'stick', amount: 2 },
    ],
    pattern: [null, 'plank', null, null, 'stick', null, null, 'stick', null],
    outputs: [{ id: 'woodenShovel', amount: 1 }],
    unlockedBy: 'craftSticks',
  },
  {
    id: 'craft_tree_tap',
    name: 'Craft Tree Tap',
    description: 'A hollow wooden tap for drawing sticky resin from rubber trees.',
    tier: 'manual',
    durationMs: 1400,
    inputs: [
      { id: 'plank', amount: 3 },
      { id: 'stick', amount: 1 },
    ],
    pattern: ['plank', 'plank', null, null, 'stick', 'plank', null, null, null],
    outputs: [{ id: 'treeTap', amount: 1 }],
    unlockedBy: 'craftSticks',
  },
  {
    id: 'craft_stone_axe',
    name: 'Craft Stone Axe',
    description: 'A cobblestone axe head on a simple stick handle.',
    tier: 'manual',
    durationMs: 1600,
    inputs: [
      { id: 'cobblestone', amount: 3 },
      { id: 'stick', amount: 2 },
    ],
    pattern: ['cobblestone', 'cobblestone', null, 'cobblestone', 'stick', null, null, 'stick', null],
    outputs: [{ id: 'stoneAxe', amount: 1 }],
    unlockedBy: 'craftSticks',
  },
  {
    id: 'craft_stone_pickaxe',
    name: 'Craft Stone Pickaxe',
    description: 'Cobblestone across the top with a pair of sturdy handles.',
    tier: 'manual',
    durationMs: 1600,
    inputs: [
      { id: 'cobblestone', amount: 3 },
      { id: 'stick', amount: 2 },
    ],
    pattern: ['cobblestone', 'cobblestone', 'cobblestone', null, 'stick', null, null, 'stick', null],
    outputs: [{ id: 'stonePickaxe', amount: 1 }],
    unlockedBy: 'craftSticks',
  },
  {
    id: 'craft_iron_axe',
    name: 'Craft Iron Axe',
    description: 'An iron axe head on a familiar stick handle.',
    tier: 'manual',
    durationMs: 1800,
    inputs: [
      { id: 'ironIngot', amount: 3 },
      { id: 'stick', amount: 2 },
    ],
    pattern: ['ironIngot', 'ironIngot', null, 'ironIngot', 'stick', null, null, 'stick', null],
    outputs: [{ id: 'ironAxe', amount: 1 }],
    unlockedBy: 'firstDirt',
  },
  {
    id: 'craft_iron_pickaxe',
    name: 'Craft Iron Pickaxe',
    description: 'Iron across the top for the first serious mining step.',
    tier: 'manual',
    durationMs: 1800,
    inputs: [
      { id: 'ironIngot', amount: 3 },
      { id: 'stick', amount: 2 },
    ],
    pattern: ['ironIngot', 'ironIngot', 'ironIngot', null, 'stick', null, null, 'stick', null],
    outputs: [{ id: 'ironPickaxe', amount: 1 }],
    unlockedBy: 'firstDirt',
  },
  {
    id: 'craft_iron_shovel',
    name: 'Craft Iron Shovel',
    description: 'An iron shovel head on a familiar stick handle.',
    tier: 'manual',
    durationMs: 1700,
    inputs: [
      { id: 'ironIngot', amount: 1 },
      { id: 'stick', amount: 2 },
    ],
    pattern: [null, 'ironIngot', null, null, 'stick', null, null, 'stick', null],
    outputs: [{ id: 'ironShovel', amount: 1 }],
    unlockedBy: 'firstDirt',
  },
  {
    id: 'knap_flint',
    name: 'Knap Flint',
    description: 'Pick through gravel until a sharp flint piece turns up.',
    tier: 'manual',
    durationMs: 900,
    inputs: [{ id: 'gravel', amount: 2 }],
    outputs: [{ id: 'flint', amount: 1 }],
    unlockedBy: 'firstDirt',
  },
  {
    id: 'craft_stone_hammer',
    name: 'Craft Stone Hammer',
    description: 'A crude hammer for breaking ore into better furnace feed.',
    tier: 'manual',
    durationMs: 1600,
    inputs: [
      { id: 'cobblestone', amount: 6 },
      { id: 'stick', amount: 1 },
    ],
    pattern: ['cobblestone', 'cobblestone', null, 'cobblestone', 'cobblestone', 'stick', 'cobblestone', 'cobblestone', null],
    outputs: [{ id: 'stoneHammer', amount: 1 }],
    unlockedBy: 'craftSticks',
  },
  {
    id: 'craft_iron_hammer',
    name: 'Craft Iron Hammer',
    description: 'A heavier hammer that lasts much longer than stone.',
    tier: 'manual',
    durationMs: 1800,
    inputs: [
      { id: 'ironIngot', amount: 6 },
      { id: 'stick', amount: 1 },
    ],
    pattern: ['ironIngot', 'ironIngot', null, 'ironIngot', 'ironIngot', 'stick', 'ironIngot', 'ironIngot', null],
    outputs: [{ id: 'ironHammer', amount: 1 }],
    unlockedBy: 'firstDirt',
  },
  {
    id: 'crush_iron_ore',
    name: 'Crush Iron Ore',
    description: 'Hammer iron ore into a richer furnace feed.',
    tier: 'manual',
    durationMs: 1800,
    inputs: [{ id: 'ironOre', amount: 1 }],
    catalysts: [{ id: 'stoneHammer', amount: 1 }],
    durabilityCosts: [{ id: 'stoneHammer', amount: 1 }],
    pattern: [null, 'stoneHammer', null, null, 'ironOre', null, null, null, null],
    outputs: [{ id: 'crushedIronOre', amount: 2 }],
    unlockedBy: 'firstDirt',
  },
  {
    id: 'crush_copper_ore',
    name: 'Crush Copper Ore',
    description: 'Hammer copper ore into a richer furnace feed.',
    tier: 'bronze',
    durationMs: 1800,
    inputs: [{ id: 'copperOre', amount: 1 }],
    catalysts: [{ id: 'stoneHammer', amount: 1 }],
    durabilityCosts: [{ id: 'stoneHammer', amount: 1 }],
    pattern: [null, 'stoneHammer', null, null, 'copperOre', null, null, null, null],
    outputs: [{ id: 'crushedCopperOre', amount: 2 }],
    unlockedBy: 'copperAndTin',
  },
  {
    id: 'crush_tin_ore',
    name: 'Crush Tin Ore',
    description: 'Hammer tin ore into a richer furnace feed.',
    tier: 'bronze',
    durationMs: 1800,
    inputs: [{ id: 'tinOre', amount: 1 }],
    catalysts: [{ id: 'stoneHammer', amount: 1 }],
    durabilityCosts: [{ id: 'stoneHammer', amount: 1 }],
    pattern: [null, 'stoneHammer', null, null, 'tinOre', null, null, null, null],
    outputs: [{ id: 'crushedTinOre', amount: 2 }],
    unlockedBy: 'copperAndTin',
  },
  {
    id: 'craft_mortar',
    name: 'Craft Pestle & Mortar',
    description: 'A rough stone cup and pestle for grinding early ingots into dust.',
    tier: 'manual',
    durationMs: 1400,
    inputs: [
      { id: 'cobblestone', amount: 3 },
      { id: 'flint', amount: 1 },
      { id: 'stick', amount: 1 },
    ],
    pattern: ['cobblestone', 'flint', 'cobblestone', null, 'cobblestone', null, null, 'stick', null],
    outputs: [{ id: 'mortar', amount: 1 }],
    unlockedBy: 'craftSticks',
  },
  {
    id: 'craft_stone_shovel',
    name: 'Craft Stone Shovel',
    description: 'A cobblestone shovel head on a pair of simple handles.',
    tier: 'manual',
    durationMs: 1500,
    inputs: [
      { id: 'cobblestone', amount: 1 },
      { id: 'stick', amount: 2 },
    ],
    pattern: [null, 'cobblestone', null, null, 'stick', null, null, 'stick', null],
    outputs: [{ id: 'stoneShovel', amount: 1 }],
    unlockedBy: 'craftSticks',
  },
  {
    id: 'craft_iron_mortar',
    name: 'Craft Iron Pestle & Mortar',
    description: 'Iron plates form a sturdier grinding cup with a simple handle.',
    tier: 'manual',
    durationMs: 2200,
    inputs: [
      { id: 'ironPlate', amount: 3 },
      { id: 'flint', amount: 1 },
      { id: 'stick', amount: 1 },
    ],
    pattern: ['ironPlate', 'flint', 'ironPlate', null, 'ironPlate', null, null, 'stick', null],
    outputs: [{ id: 'ironMortar', amount: 1 }],
    unlockedBy: 'firstDirt',
  },
  {
    id: 'craft_bronze_mortar',
    name: 'Craft Bronze Pestle & Mortar',
    description: 'Bronze plates make the longest-lasting early grinding cup.',
    tier: 'bronze',
    durationMs: 2400,
    inputs: [
      { id: 'bronzePlate', amount: 3 },
      { id: 'flint', amount: 1 },
      { id: 'stick', amount: 1 },
    ],
    pattern: ['bronzePlate', 'flint', 'bronzePlate', null, 'bronzePlate', null, null, 'stick', null],
    outputs: [{ id: 'bronzeMortar', amount: 1 }],
    unlockedBy: 'bronzeAge',
  },
  {
    id: 'build_furnace',
    name: 'Build Primitive Furnace',
    description: 'Eight cobblestone make a fuel-fed box for slow ore smelting.',
    tier: 'manual',
    durationMs: 5000,
    inputs: [{ id: 'cobblestone', amount: 8 }],
    pattern: ['cobblestone', 'cobblestone', 'cobblestone', 'cobblestone', null, 'cobblestone', 'cobblestone', 'cobblestone', 'cobblestone'],
    outputs: [],
    machineOutputs: [{ id: 'furnace', amount: 1 }],
    unlockedBy: 'firstDirt',
  },
  {
    id: 'craft_unfired_brick',
    name: 'Mold Unfired Brick',
    description: 'Press a lump of clay into a brick shape before firing it.',
    tier: 'bronze',
    durationMs: 1000,
    inputs: [{ id: 'clay', amount: 1 }],
    outputs: [{ id: 'unfiredBrick', amount: 1 }],
    unlockedBy: 'bronzeAge',
  },
  {
    id: 'craft_bucket',
    name: 'Craft Bucket',
    description: 'Three iron plates folded into a simple water bucket.',
    tier: 'bronze',
    durationMs: 1800,
    inputs: [{ id: 'ironPlate', amount: 3 }],
    pattern: ['ironPlate', null, 'ironPlate', null, 'ironPlate', null, null, null, null],
    outputs: [{ id: 'bucket', amount: 1 }],
    unlockedBy: 'bronzeAge',
  },
  {
    id: 'craft_pipe_sealant',
    name: 'Cook Pipe Sealant',
    description: 'Sticky resin boiled into a simple sealant for early fluid handling.',
    tier: 'steam',
    durationMs: 1800,
    inputs: [{ id: 'rubberSap', amount: 2 }],
    outputs: [{ id: 'pipeSealant', amount: 1 }],
    unlockedBy: 'bronzeAge',
  },
  {
    id: 'craft_coke_oven_brick',
    name: 'Pack Coke Oven Bricks',
    description: 'Brick, clay, and sand make refractory blocks for the first creosote oven.',
    tier: 'steam',
    durationMs: 3000,
    inputs: [
      { id: 'brick', amount: 2 },
      { id: 'clay', amount: 1 },
      { id: 'sand', amount: 1 },
    ],
    pattern: ['brick', 'clay', 'brick', null, 'sand', null, null, null, null],
    outputs: [{ id: 'cokeOvenBrick', amount: 2 }],
    unlockedBy: 'bronzeAge',
  },
  {
    id: 'craft_firebrick',
    name: 'Pack Firebricks',
    description: 'Dense sanded brick for the first bricked blast furnace.',
    tier: 'steam',
    durationMs: 3200,
    inputs: [
      { id: 'brick', amount: 2 },
      { id: 'sand', amount: 2 },
    ],
    pattern: ['brick', 'sand', 'brick', null, 'sand', null, null, null, null],
    outputs: [{ id: 'firebrick', amount: 2 }],
    unlockedBy: 'bronzeAge',
  },
  {
    id: 'build_well',
    name: 'Build Well',
    description: 'A brick ring and bucket make the first steady water source.',
    tier: 'steam',
    durationMs: 5000,
    inputs: [
      { id: 'brick', amount: 8 },
      { id: 'bucket', amount: 1 },
    ],
    pattern: ['brick', 'brick', 'brick', 'brick', 'bucket', 'brick', 'brick', 'brick', 'brick'],
    outputs: [],
    machineOutputs: [{ id: 'well', amount: 1 }],
    unlockedBy: 'bronzeAge',
  },
  {
    id: 'build_steam_boiler',
    name: 'Build Steam Boiler',
    description: 'A bronze boiler shell that turns fuel and well water into steam.',
    tier: 'steam',
    durationMs: 6500,
    inputs: [
      { id: 'steamCasing', amount: 1 },
      { id: 'bronzePlate', amount: 4 },
      { id: 'copperRod', amount: 2 },
    ],
    pattern: ['bronzePlate', 'copperRod', 'bronzePlate', 'bronzePlate', 'steamCasing', 'bronzePlate', null, 'copperRod', null],
    outputs: [],
    machineOutputs: [{ id: 'steamBoiler', amount: 1 }],
    unlockedBy: 'bronzeAge',
  },
  {
    id: 'build_steam_tank',
    name: 'Build Iron Steam Tank',
    description: 'Iron plates and a bucket make a small buffer for awkward early steam layouts.',
    tier: 'steam',
    durationMs: 6500,
    inputs: [
      { id: 'ironPlate', amount: 8 },
      { id: 'bucket', amount: 1 },
    ],
    pattern: ['ironPlate', 'ironPlate', 'ironPlate', 'ironPlate', 'bucket', 'ironPlate', 'ironPlate', 'ironPlate', 'ironPlate'],
    outputs: [],
    machineOutputs: [{ id: 'steamTank', amount: 1 }],
    unlockedBy: 'bronzeAge',
  },
  {
    id: 'build_copper_pipe',
    name: 'Build Copper Steam Pipes',
    description: 'Basic copper pipework for slow steam transfer.',
    tier: 'steam',
    durationMs: 3200,
    inputs: [
      { id: 'copperPlate', amount: 2 },
      { id: 'copperRod', amount: 1 },
    ],
    pattern: [null, null, null, 'copperPlate', 'copperRod', 'copperPlate', null, null, null],
    outputs: [],
    machineOutputs: [{ id: 'copperPipe', amount: 4 }],
    unlockedBy: 'bronzeAge',
  },
  {
    id: 'build_bronze_pipe',
    name: 'Build Bronze Steam Pipes',
    description: 'Bronze pipework with a better transfer rate.',
    tier: 'steam',
    durationMs: 3600,
    inputs: [
      { id: 'bronzePlate', amount: 2 },
      { id: 'bronzeRod', amount: 1 },
    ],
    pattern: [null, null, null, 'bronzePlate', 'bronzeRod', 'bronzePlate', null, null, null],
    outputs: [],
    machineOutputs: [{ id: 'bronzePipe', amount: 4 }],
    unlockedBy: 'bronzeAge',
  },
  {
    id: 'build_iron_pipe',
    name: 'Build Iron Steam Pipes',
    description: 'Wide iron pipework for fast steam transfer.',
    tier: 'steam',
    durationMs: 4000,
    inputs: [
      { id: 'ironPlate', amount: 2 },
      { id: 'ironRod', amount: 1 },
    ],
    pattern: [null, null, null, 'ironPlate', 'ironRod', 'ironPlate', null, null, null],
    outputs: [],
    machineOutputs: [{ id: 'ironPipe', amount: 4 }],
    unlockedBy: 'bronzeAge',
  },
  {
    id: 'craft_steam_casing',
    name: 'Craft Steam Casing',
    description: 'Bronze plates and rods riveted into a basic steam machine shell.',
    tier: 'steam',
    durationMs: 4000,
    inputs: [
      { id: 'bronzePlate', amount: 4 },
      { id: 'bronzeRod', amount: 2 },
    ],
    pattern: ['bronzePlate', 'bronzeRod', 'bronzePlate', 'bronzePlate', null, 'bronzePlate', null, 'bronzeRod', null],
    outputs: [{ id: 'steamCasing', amount: 1 }],
    unlockedBy: 'bronzeAge',
  },
  {
    id: 'build_steam_macerator',
    name: 'Build Steam Macerator',
    description: 'A steam-driven grinder for ores and dusts.',
    tier: 'steam',
    durationMs: 7000,
    inputs: [
      { id: 'steamCasing', amount: 1 },
      { id: 'bronzePlate', amount: 4 },
      { id: 'bronzeRod', amount: 2 },
      { id: 'bronzeMortar', amount: 1 },
    ],
    pattern: ['bronzePlate', 'bronzeRod', 'bronzePlate', 'bronzePlate', 'steamCasing', 'bronzePlate', null, 'bronzeMortar', 'bronzeRod'],
    outputs: [],
    machineOutputs: [{ id: 'steamMacerator', amount: 1 }],
    unlockedBy: 'bronzeAge',
  },
  {
    id: 'build_steam_forge_hammer',
    name: 'Build Steam Forge Hammer',
    description: 'A bronze hammer frame that automates plate work.',
    tier: 'steam',
    durationMs: 7000,
    inputs: [
      { id: 'steamCasing', amount: 1 },
      { id: 'bronzePlate', amount: 4 },
      { id: 'bronzeRod', amount: 2 },
      { id: 'ironHammer', amount: 1 },
    ],
    pattern: ['bronzePlate', 'bronzeRod', 'bronzePlate', 'bronzePlate', 'steamCasing', 'bronzePlate', null, 'ironHammer', 'bronzeRod'],
    outputs: [],
    machineOutputs: [{ id: 'steamForgeHammer', amount: 1 }],
    unlockedBy: 'bronzeAge',
  },
  {
    id: 'build_steam_compressor',
    name: 'Build Steam Compressor',
    description: 'A compact bronze press for ceramic and metal compression.',
    tier: 'steam',
    durationMs: 7000,
    inputs: [
      { id: 'steamCasing', amount: 1 },
      { id: 'bronzePlate', amount: 6 },
      { id: 'bronzeRod', amount: 1 },
    ],
    pattern: ['bronzePlate', 'bronzeRod', 'bronzePlate', 'bronzePlate', 'steamCasing', 'bronzePlate', 'bronzePlate', null, 'bronzePlate'],
    outputs: [],
    machineOutputs: [{ id: 'steamCompressor', amount: 1 }],
    unlockedBy: 'bronzeAge',
  },
  {
    id: 'build_steam_extractor',
    name: 'Build Steam Extractor',
    description: 'A bronze extractor for sticky resin and early rubber prep.',
    tier: 'steam',
    durationMs: 7000,
    inputs: [
      { id: 'steamCasing', amount: 1 },
      { id: 'bronzePlate', amount: 4 },
      { id: 'copperRod', amount: 2 },
      { id: 'bucket', amount: 1 },
    ],
    pattern: ['bronzePlate', 'copperRod', 'bronzePlate', 'bronzePlate', 'steamCasing', 'bronzePlate', null, 'bucket', null],
    outputs: [],
    machineOutputs: [{ id: 'steamExtractor', amount: 1 }],
    unlockedBy: 'bronzeAge',
  },
  {
    id: 'build_steam_alloy_smelter',
    name: 'Build Steam Alloy Smelter',
    description: 'A bronze alloy box for automated bronze firing.',
    tier: 'steam',
    durationMs: 7200,
    inputs: [
      { id: 'steamCasing', amount: 1 },
      { id: 'bronzePlate', amount: 6 },
      { id: 'firebrick', amount: 2 },
    ],
    pattern: ['bronzePlate', 'firebrick', 'bronzePlate', 'bronzePlate', 'steamCasing', 'bronzePlate', 'bronzePlate', 'firebrick', 'bronzePlate'],
    outputs: [],
    machineOutputs: [{ id: 'steamAlloySmelter', amount: 1 }],
    unlockedBy: 'bronzeAge',
  },
  {
    id: 'build_steam_furnace',
    name: 'Build Steam Furnace',
    description: 'A bronze steam oven that smelts much faster than the primitive furnace.',
    tier: 'steam',
    durationMs: 7000,
    inputs: [
      { id: 'steamCasing', amount: 1 },
      { id: 'bronzePlate', amount: 4 },
      { id: 'brick', amount: 2 },
    ],
    pattern: ['bronzePlate', 'brick', 'bronzePlate', 'bronzePlate', 'steamCasing', 'bronzePlate', null, 'brick', null],
    outputs: [],
    machineOutputs: [{ id: 'steamFurnace', amount: 1 }],
    unlockedBy: 'bronzeAge',
  },
  {
    id: 'build_coke_oven',
    name: 'Build Coke Oven',
    description: 'A slow refractory oven for charcoal, coal coke, and first creosote.',
    tier: 'steam',
    durationMs: 9000,
    inputs: [
      { id: 'cokeOvenBrick', amount: 8 },
      { id: 'pipeSealant', amount: 1 },
    ],
    pattern: ['cokeOvenBrick', 'cokeOvenBrick', 'cokeOvenBrick', 'cokeOvenBrick', 'pipeSealant', 'cokeOvenBrick', 'cokeOvenBrick', 'cokeOvenBrick', 'cokeOvenBrick'],
    outputs: [],
    machineOutputs: [{ id: 'cokeOven', amount: 1 }],
    unlockedBy: 'bronzeAge',
  },
  {
    id: 'craft_bbf_casing',
    name: 'Craft BBF Casing',
    description: 'Firebrick plates bolted into one dense blast furnace casing block.',
    tier: 'steam',
    durationMs: 5500,
    inputs: [
      { id: 'firebrick', amount: 4 },
      { id: 'ironPlate', amount: 1 },
    ],
    catalysts: [{ id: 'bronzeWrench', amount: 1 }],
    durabilityCosts: [{ id: 'bronzeWrench', amount: 1 }],
    pattern: ['firebrick', 'ironPlate', 'firebrick', null, 'bronzeWrench', null, 'firebrick', null, 'firebrick'],
    outputs: [{ id: 'bbfCasing', amount: 1 }],
    unlockedBy: 'bronzeAge',
  },
  {
    id: 'build_bricked_blast_furnace',
    name: 'Assemble BBF Multiblock',
    description: 'Lay out four BBF Casings in a 2x2 to stage the factory-floor blast furnace structure.',
    tier: 'steam',
    recipeType: 'machine',
    durationMs: 2000,
    inputs: [{ id: 'bbfCasing', amount: 4 }],
    pattern: ['bbfCasing', 'bbfCasing', null, 'bbfCasing', 'bbfCasing', null, null, null, null],
    outputs: [],
    machineOutputs: [{ id: 'brickedBlastFurnacePart', amount: 4 }],
    unlockedBy: 'bronzeAge',
  },
  {
    id: 'bronze_blend',
    name: 'Mix Bronze Dust',
    description: 'Three copper dust and one tin dust make the first bronze batch.',
    tier: 'bronze',
    durationMs: 3500,
    inputs: [
      { id: 'copperDust', amount: 3 },
      { id: 'tinDust', amount: 1 },
    ],
    outputs: [{ id: 'bronzeBlend', amount: 4 }],
    unlockedBy: 'copperAndTin',
  },
  {
    id: 'grind_iron_ingot',
    name: 'Grind Iron Dust',
    description: 'Use the pestle and mortar to break an iron ingot into dust.',
    tier: 'manual',
    durationMs: 1600,
    inputs: [{ id: 'ironIngot', amount: 1 }],
    catalysts: [{ id: 'mortar', amount: 1 }],
    durabilityCosts: [{ id: 'mortar', amount: 1 }],
    pattern: [null, 'mortar', null, null, 'ironIngot', null, null, null, null],
    outputs: [{ id: 'ironDust', amount: 1 }],
    unlockedBy: 'firstDirt',
  },
  {
    id: 'grind_crushed_iron_ore',
    name: 'Grind Crushed Iron Dust',
    description: 'Use the pestle and mortar to grind crushed iron ore into dust.',
    tier: 'manual',
    durationMs: 1600,
    inputs: [{ id: 'crushedIronOre', amount: 1 }],
    catalysts: [{ id: 'mortar', amount: 1 }],
    durabilityCosts: [{ id: 'mortar', amount: 1 }],
    pattern: [null, 'mortar', null, null, 'crushedIronOre', null, null, null, null],
    outputs: [{ id: 'ironDust', amount: 1 }],
    unlockedBy: 'firstDirt',
  },
  {
    id: 'grind_copper_ingot',
    name: 'Grind Copper Dust',
    description: 'Use the pestle and mortar to break a copper ingot into dust.',
    tier: 'bronze',
    durationMs: 1600,
    inputs: [{ id: 'copperIngot', amount: 1 }],
    catalysts: [{ id: 'mortar', amount: 1 }],
    durabilityCosts: [{ id: 'mortar', amount: 1 }],
    pattern: [null, 'mortar', null, null, 'copperIngot', null, null, null, null],
    outputs: [{ id: 'copperDust', amount: 1 }],
    unlockedBy: 'copperAndTin',
  },
  {
    id: 'grind_crushed_copper_ore',
    name: 'Grind Crushed Copper Dust',
    description: 'Use the pestle and mortar to grind crushed copper ore into dust.',
    tier: 'bronze',
    durationMs: 1600,
    inputs: [{ id: 'crushedCopperOre', amount: 1 }],
    catalysts: [{ id: 'mortar', amount: 1 }],
    durabilityCosts: [{ id: 'mortar', amount: 1 }],
    pattern: [null, 'mortar', null, null, 'crushedCopperOre', null, null, null, null],
    outputs: [{ id: 'copperDust', amount: 1 }],
    unlockedBy: 'copperAndTin',
  },
  {
    id: 'grind_tin_ingot',
    name: 'Grind Tin Dust',
    description: 'Use the pestle and mortar to break a tin ingot into dust.',
    tier: 'bronze',
    durationMs: 1600,
    inputs: [{ id: 'tinIngot', amount: 1 }],
    catalysts: [{ id: 'mortar', amount: 1 }],
    durabilityCosts: [{ id: 'mortar', amount: 1 }],
    pattern: [null, 'mortar', null, null, 'tinIngot', null, null, null, null],
    outputs: [{ id: 'tinDust', amount: 1 }],
    unlockedBy: 'copperAndTin',
  },
  {
    id: 'grind_crushed_tin_ore',
    name: 'Grind Crushed Tin Dust',
    description: 'Use the pestle and mortar to grind crushed tin ore into dust.',
    tier: 'bronze',
    durationMs: 1600,
    inputs: [{ id: 'crushedTinOre', amount: 1 }],
    catalysts: [{ id: 'mortar', amount: 1 }],
    durabilityCosts: [{ id: 'mortar', amount: 1 }],
    pattern: [null, 'mortar', null, null, 'crushedTinOre', null, null, null, null],
    outputs: [{ id: 'tinDust', amount: 1 }],
    unlockedBy: 'copperAndTin',
  },
  {
    id: 'copper_plate',
    name: 'Hammer Copper Plate',
    description: 'Flatten copper ingots into a useful plate with a hammer.',
    tier: 'bronze',
    durationMs: 5500,
    inputs: [{ id: 'copperIngot', amount: 2 }],
    catalysts: [{ id: 'stoneHammer', amount: 1 }],
    durabilityCosts: [{ id: 'stoneHammer', amount: 1 }],
    pattern: [null, 'stoneHammer', null, null, 'copperIngot', null, null, 'copperIngot', null],
    outputs: [{ id: 'copperPlate', amount: 1 }],
    unlockedBy: 'copperAndTin',
  },
  {
    id: 'tin_plate',
    name: 'Hammer Tin Plate',
    description: 'Flatten tin ingots into soft sheets for early electrical tricks.',
    tier: 'bronze',
    durationMs: 4500,
    inputs: [{ id: 'tinIngot', amount: 2 }],
    catalysts: [{ id: 'stoneHammer', amount: 1 }],
    durabilityCosts: [{ id: 'stoneHammer', amount: 1 }],
    pattern: [null, 'stoneHammer', null, null, 'tinIngot', null, null, 'tinIngot', null],
    outputs: [{ id: 'tinPlate', amount: 1 }],
    unlockedBy: 'copperAndTin',
  },
  {
    id: 'iron_plate',
    name: 'Hammer Iron Plate',
    description: 'Flatten iron ingots into a sturdy plate.',
    tier: 'manual',
    durationMs: 5500,
    inputs: [{ id: 'ironIngot', amount: 2 }],
    catalysts: [{ id: 'stoneHammer', amount: 1 }],
    durabilityCosts: [{ id: 'stoneHammer', amount: 1 }],
    pattern: [null, 'stoneHammer', null, null, 'ironIngot', null, null, 'ironIngot', null],
    outputs: [{ id: 'ironPlate', amount: 1 }],
    unlockedBy: 'firstDirt',
  },
  {
    id: 'bronze_plate',
    name: 'Hammer Bronze Plate',
    description: 'Flatten bronze ingots into a machine-ready plate.',
    tier: 'bronze',
    durationMs: 5500,
    inputs: [{ id: 'bronzeIngot', amount: 2 }],
    catalysts: [{ id: 'stoneHammer', amount: 1 }],
    durabilityCosts: [{ id: 'stoneHammer', amount: 1 }],
    pattern: [null, 'stoneHammer', null, null, 'bronzeIngot', null, null, 'bronzeIngot', null],
    outputs: [{ id: 'bronzePlate', amount: 1 }],
    unlockedBy: 'bronzeAge',
  },
  {
    id: 'steel_plate',
    name: 'Hammer Steel Plate',
    description: 'Flatten steel ingots into the first stronger machine plates.',
    tier: 'steam',
    durationMs: 6500,
    inputs: [{ id: 'steelIngot', amount: 2 }],
    catalysts: [{ id: 'stoneHammer', amount: 1 }],
    durabilityCosts: [{ id: 'stoneHammer', amount: 1 }],
    pattern: [null, 'stoneHammer', null, null, 'steelIngot', null, null, 'steelIngot', null],
    outputs: [{ id: 'steelPlate', amount: 1 }],
    unlockedBy: 'bronzeAge',
  },
  {
    id: 'craft_iron_file',
    name: 'Craft Iron File',
    description: 'Two iron plates and a handle make the first filing tool.',
    tier: 'manual',
    durationMs: 2400,
    inputs: [
      { id: 'ironPlate', amount: 2 },
      { id: 'stick', amount: 1 },
    ],
    pattern: [null, 'ironPlate', null, null, 'ironPlate', null, null, 'stick', null],
    outputs: [{ id: 'ironFile', amount: 1 }],
    unlockedBy: 'firstDirt',
  },
  {
    id: 'craft_bronze_file',
    name: 'Craft Bronze File',
    description: 'Two bronze plates and a handle make a longer-lasting filing tool.',
    tier: 'bronze',
    durationMs: 2600,
    inputs: [
      { id: 'bronzePlate', amount: 2 },
      { id: 'stick', amount: 1 },
    ],
    pattern: [null, 'bronzePlate', null, null, 'bronzePlate', null, null, 'stick', null],
    outputs: [{ id: 'bronzeFile', amount: 1 }],
    unlockedBy: 'bronzeAge',
  },
  {
    id: 'craft_iron_wrench',
    name: 'Craft Iron Wrench',
    description: 'A heavy ingot-built wrench for early assembly work.',
    tier: 'manual',
    durationMs: 2600,
    inputs: [{ id: 'ironIngot', amount: 6 }],
    pattern: ['ironIngot', null, 'ironIngot', 'ironIngot', 'ironIngot', 'ironIngot', null, 'ironIngot', null],
    outputs: [{ id: 'ironWrench', amount: 1 }],
    unlockedBy: 'firstDirt',
  },
  {
    id: 'craft_bronze_wrench',
    name: 'Craft Bronze Wrench',
    description: 'A softer bronze wrench for the first metal workshop.',
    tier: 'bronze',
    durationMs: 2600,
    inputs: [{ id: 'bronzeIngot', amount: 6 }],
    pattern: ['bronzeIngot', null, 'bronzeIngot', 'bronzeIngot', 'bronzeIngot', 'bronzeIngot', null, 'bronzeIngot', null],
    outputs: [{ id: 'bronzeWrench', amount: 1 }],
    unlockedBy: 'bronzeAge',
  },
  {
    id: 'file_iron_rod',
    name: 'File Iron Rod',
    description: 'File one ingot down into one rough rod.',
    tier: 'manual',
    durationMs: 2400,
    inputs: [{ id: 'ironIngot', amount: 1 }],
    catalysts: [{ id: 'ironFile', amount: 1 }],
    durabilityCosts: [{ id: 'ironFile', amount: 1 }],
    pattern: [null, 'ironFile', null, null, 'ironIngot', null, null, null, null],
    outputs: [{ id: 'ironRod', amount: 1 }],
    unlockedBy: 'firstDirt',
  },
  {
    id: 'file_copper_rod',
    name: 'File Copper Rod',
    description: 'File one copper ingot down into one rough rod.',
    tier: 'bronze',
    durationMs: 2400,
    inputs: [{ id: 'copperIngot', amount: 1 }],
    catalysts: [{ id: 'ironFile', amount: 1 }],
    durabilityCosts: [{ id: 'ironFile', amount: 1 }],
    pattern: [null, 'ironFile', null, null, 'copperIngot', null, null, null, null],
    outputs: [{ id: 'copperRod', amount: 1 }],
    unlockedBy: 'copperAndTin',
  },
  {
    id: 'file_tin_rod',
    name: 'File Tin Rod',
    description: 'File one tin ingot down into one rough rod.',
    tier: 'bronze',
    durationMs: 2400,
    inputs: [{ id: 'tinIngot', amount: 1 }],
    catalysts: [{ id: 'ironFile', amount: 1 }],
    durabilityCosts: [{ id: 'ironFile', amount: 1 }],
    pattern: [null, 'ironFile', null, null, 'tinIngot', null, null, null, null],
    outputs: [{ id: 'tinRod', amount: 1 }],
    unlockedBy: 'copperAndTin',
  },
  {
    id: 'file_bronze_rod',
    name: 'File Bronze Rod',
    description: 'File one bronze ingot down into one rough rod.',
    tier: 'bronze',
    durationMs: 2400,
    inputs: [{ id: 'bronzeIngot', amount: 1 }],
    catalysts: [{ id: 'ironFile', amount: 1 }],
    durabilityCosts: [{ id: 'ironFile', amount: 1 }],
    pattern: [null, 'ironFile', null, null, 'bronzeIngot', null, null, null, null],
    outputs: [{ id: 'bronzeRod', amount: 1 }],
    unlockedBy: 'bronzeAge',
  },
  {
    id: 'file_steel_rod',
    name: 'File Steel Rod',
    description: 'File one steel ingot into a sturdy rod for early electronics frames.',
    tier: 'steam',
    durationMs: 2800,
    inputs: [{ id: 'steelIngot', amount: 1 }],
    catalysts: [{ id: 'ironFile', amount: 1 }],
    durabilityCosts: [{ id: 'ironFile', amount: 1 }],
    pattern: [null, 'ironFile', null, null, 'steelIngot', null, null, null, null],
    outputs: [{ id: 'steelRod', amount: 1 }],
    unlockedBy: 'firstSteel',
  },
  {
    id: 'file_copper_wire',
    name: 'Draw Copper Wire',
    description: 'Draw a copper rod into rough wire with a file.',
    tier: 'steam',
    durationMs: 2400,
    inputs: [{ id: 'copperRod', amount: 1 }],
    catalysts: [{ id: 'ironFile', amount: 1 }],
    durabilityCosts: [{ id: 'ironFile', amount: 1 }],
    pattern: [null, 'ironFile', null, null, 'copperRod', null, null, null, null],
    outputs: [{ id: 'copperWire', amount: 2 }],
    unlockedBy: 'copperAndTin',
  },
  {
    id: 'file_glass_tube',
    name: 'File Glass Tubes',
    description: 'Score glass into fragile tubes for the first vacuum valves.',
    tier: 'steam',
    durationMs: 2600,
    inputs: [{ id: 'glass', amount: 1 }],
    catalysts: [{ id: 'ironFile', amount: 1 }],
    durabilityCosts: [{ id: 'ironFile', amount: 1 }],
    pattern: [null, 'ironFile', null, null, 'glass', null, null, null, null],
    outputs: [{ id: 'glassTube', amount: 2 }],
    unlockedBy: 'steelPlateQuest',
  },
  {
    id: 'file_red_alloy_wire',
    name: 'Draw Red Alloy Wire',
    description: 'File red alloy into soft conductive wire.',
    tier: 'steam',
    durationMs: 2600,
    inputs: [{ id: 'redAlloyIngot', amount: 1 }],
    catalysts: [{ id: 'ironFile', amount: 1 }],
    durabilityCosts: [{ id: 'ironFile', amount: 1 }],
    pattern: [null, 'ironFile', null, null, 'redAlloyIngot', null, null, null, null],
    outputs: [{ id: 'redAlloyWire', amount: 2 }],
    unlockedBy: 'steelPlateQuest',
  },
  {
    id: 'grind_carbon_dust',
    name: 'Grind Carbon Dust',
    description: 'Crush coal into carbon dust for crude resistors.',
    tier: 'steam',
    durationMs: 1800,
    inputs: [{ id: 'coal', amount: 1 }],
    catalysts: [{ id: 'mortar', amount: 1 }],
    durabilityCosts: [{ id: 'mortar', amount: 1 }],
    pattern: [null, 'mortar', null, null, 'coal', null, null, null, null],
    outputs: [{ id: 'carbonDust', amount: 1 }],
    unlockedBy: 'steelPlateQuest',
  },
  {
    id: 'insulate_copper_wire',
    name: 'Insulate Copper Wire',
    description: 'Wrap copper wire in rubber for the first safe circuit wiring.',
    tier: 'steam',
    durationMs: 1800,
    inputs: [
      { id: 'copperWire', amount: 1 },
      { id: 'rubber', amount: 1 },
    ],
    pattern: ['rubber', null, null, 'copperWire', null, null, null, null, null],
    outputs: [{ id: 'conductiveWire', amount: 1 }],
    unlockedBy: 'steelPlateQuest',
  },
  {
    id: 'craft_resistor',
    name: 'Craft Resistor',
    description: 'Bind carbon dust with copper wire into a primitive resistor.',
    tier: 'steam',
    durationMs: 1800,
    inputs: [
      { id: 'carbonDust', amount: 1 },
      { id: 'copperWire', amount: 2 },
    ],
    pattern: [null, 'copperWire', null, null, 'carbonDust', null, null, 'copperWire', null],
    outputs: [{ id: 'resistor', amount: 2 }],
    unlockedBy: 'steelPlateQuest',
  },
  {
    id: 'craft_basic_board',
    name: 'Coat Circuit Board',
    description: 'Press wood pulp, rubber, and copper wire into a crude coated board.',
    tier: 'steam',
    durationMs: 3000,
    inputs: [
      { id: 'woodPulp', amount: 2 },
      { id: 'rubber', amount: 1 },
      { id: 'copperWire', amount: 1 },
    ],
    pattern: ['woodPulp', 'rubber', 'woodPulp', null, 'copperWire', null, null, null, null],
    outputs: [{ id: 'basicBoard', amount: 1 }],
    unlockedBy: 'steelPlateQuest',
  },
  {
    id: 'craft_vacuum_tube',
    name: 'Craft Vacuum Tube',
    description: 'Glass, red alloy, copper, and steel form the first fragile logic valve.',
    tier: 'steam',
    durationMs: 3600,
    inputs: [
      { id: 'glassTube', amount: 1 },
      { id: 'redAlloyWire', amount: 1 },
      { id: 'copperWire', amount: 1 },
      { id: 'steelRod', amount: 1 },
    ],
    pattern: [null, 'glassTube', null, 'redAlloyWire', 'steelRod', 'copperWire', null, null, null],
    outputs: [{ id: 'vacuumTube', amount: 1 }],
    unlockedBy: 'steelPlateQuest',
  },
  {
    id: 'craft_basic_electronic_circuit',
    name: 'Craft Basic Electronic Circuit',
    description: 'Assemble the first LV circuit from a coated board, valves, wire, and steel support.',
    tier: 'lv',
    durationMs: 6000,
    inputs: [
      { id: 'basicBoard', amount: 1 },
      { id: 'conductiveWire', amount: 2 },
      { id: 'resistor', amount: 2 },
      { id: 'vacuumTube', amount: 2 },
      { id: 'redstoneDust', amount: 1 },
      { id: 'steelPlate', amount: 1 },
    ],
    pattern: ['conductiveWire', 'vacuumTube', 'conductiveWire', 'resistor', 'basicBoard', 'resistor', 'redstoneDust', 'steelPlate', 'vacuumTube'],
    outputs: [{ id: 'primitiveCircuit', amount: 1 }],
    unlockedBy: 'steelPlateQuest',
  },
]

export const fuelDefinitions: Record<string, FuelDefinition> = {
  stick: { id: 'stick', burnMs: 1200 },
  plank: { id: 'plank', burnMs: 3200 },
  log: { id: 'log', burnMs: 10000 },
  charcoal: { id: 'charcoal', burnMs: 30000 },
  coal: { id: 'coal', burnMs: 80000 },
  coalCoke: { id: 'coalCoke', burnMs: 120000 },
}

export const processRecipes: ProcessRecipe[] = [
  {
    id: 'fire_brick',
    name: 'Fire Brick',
    description: 'Bake an unfired clay brick into a sturdy brick.',
    tier: 'bronze',
    machineId: 'furnace',
    durationMs: 8000,
    input: { id: 'unfiredBrick', amount: 1 },
    output: { id: 'brick', amount: 1 },
  },
  {
    id: 'charcoal_from_log',
    name: 'Charcoal From Log',
    description: 'Bake logs into a cleaner early fuel.',
    tier: 'manual',
    machineId: 'furnace',
    durationMs: 10000,
    input: { id: 'log', amount: 1 },
    output: { id: 'charcoal', amount: 1 },
  },
  {
    id: 'smelt_iron_ingot',
    name: 'Smelt Iron Ingot',
    description: 'Slowly smelt iron ore into a tool-ready ingot.',
    tier: 'bronze',
    machineId: 'furnace',
    durationMs: 14000,
    input: { id: 'ironOre', amount: 1 },
    output: { id: 'ironIngot', amount: 1 },
  },
  {
    id: 'smelt_crushed_iron_ingot',
    name: 'Smelt Crushed Iron',
    description: 'Smelt crushed iron ore into a tool-ready ingot.',
    tier: 'bronze',
    machineId: 'furnace',
    durationMs: 14000,
    input: { id: 'crushedIronOre', amount: 1 },
    output: { id: 'ironIngot', amount: 1 },
  },
  {
    id: 'smelt_copper_ingot',
    name: 'Smelt Copper Ingot',
    description: 'Slowly smelt copper ore into a usable ingot.',
    tier: 'bronze',
    machineId: 'furnace',
    durationMs: 12000,
    input: { id: 'copperOre', amount: 1 },
    output: { id: 'copperIngot', amount: 1 },
  },
  {
    id: 'smelt_crushed_copper_ingot',
    name: 'Smelt Crushed Copper',
    description: 'Smelt crushed copper ore into a usable ingot.',
    tier: 'bronze',
    machineId: 'furnace',
    durationMs: 12000,
    input: { id: 'crushedCopperOre', amount: 1 },
    output: { id: 'copperIngot', amount: 1 },
  },
  {
    id: 'smelt_tin_ingot',
    name: 'Smelt Tin Ingot',
    description: 'Slowly smelt tin ore into a usable ingot.',
    tier: 'bronze',
    machineId: 'furnace',
    durationMs: 12000,
    input: { id: 'tinOre', amount: 1 },
    output: { id: 'tinIngot', amount: 1 },
  },
  {
    id: 'smelt_crushed_tin_ingot',
    name: 'Smelt Crushed Tin',
    description: 'Smelt crushed tin ore into a usable ingot.',
    tier: 'bronze',
    machineId: 'furnace',
    durationMs: 12000,
    input: { id: 'crushedTinOre', amount: 1 },
    output: { id: 'tinIngot', amount: 1 },
  },
  {
    id: 'smelt_bronze_ingot',
    name: 'Smelt Bronze Ingot',
    description: 'Fire bronze dust into a first proper bronze ingot.',
    tier: 'bronze',
    machineId: 'furnace',
    durationMs: 14000,
    input: { id: 'bronzeBlend', amount: 1 },
    output: { id: 'bronzeIngot', amount: 1 },
  },
  {
    id: 'steam_crush_iron_ore',
    name: 'Steam Crush Iron Ore',
    description: 'Use steam power to crush iron ore into richer furnace feed.',
    tier: 'steam',
    machineId: 'steamMacerator',
    durationMs: 7000,
    steamCostLitres: 32,
    input: { id: 'ironOre', amount: 1 },
    output: { id: 'crushedIronOre', amount: 2 },
  },
  {
    id: 'steam_crush_copper_ore',
    name: 'Steam Crush Copper Ore',
    description: 'Use steam power to crush copper ore into richer furnace feed.',
    tier: 'steam',
    machineId: 'steamMacerator',
    durationMs: 7000,
    steamCostLitres: 32,
    input: { id: 'copperOre', amount: 1 },
    output: { id: 'crushedCopperOre', amount: 2 },
  },
  {
    id: 'steam_crush_tin_ore',
    name: 'Steam Crush Tin Ore',
    description: 'Use steam power to crush tin ore into richer furnace feed.',
    tier: 'steam',
    machineId: 'steamMacerator',
    durationMs: 7000,
    steamCostLitres: 32,
    input: { id: 'tinOre', amount: 1 },
    output: { id: 'crushedTinOre', amount: 2 },
  },
  {
    id: 'steam_grind_crushed_iron_ore',
    name: 'Steam Grind Crushed Iron',
    description: 'Use steam power to grind crushed iron ore into dust.',
    tier: 'steam',
    machineId: 'steamMacerator',
    durationMs: 6000,
    steamCostLitres: 16,
    input: { id: 'crushedIronOre', amount: 1 },
    output: { id: 'ironDust', amount: 1 },
  },
  {
    id: 'steam_grind_crushed_copper_ore',
    name: 'Steam Grind Crushed Copper',
    description: 'Use steam power to grind crushed copper ore into dust.',
    tier: 'steam',
    machineId: 'steamMacerator',
    durationMs: 6000,
    steamCostLitres: 16,
    input: { id: 'crushedCopperOre', amount: 1 },
    output: { id: 'copperDust', amount: 1 },
  },
  {
    id: 'steam_grind_crushed_tin_ore',
    name: 'Steam Grind Crushed Tin',
    description: 'Use steam power to grind crushed tin ore into dust.',
    tier: 'steam',
    machineId: 'steamMacerator',
    durationMs: 6000,
    steamCostLitres: 16,
    input: { id: 'crushedTinOre', amount: 1 },
    output: { id: 'tinDust', amount: 1 },
  },
  {
    id: 'steam_grind_iron_ingot',
    name: 'Steam Grind Iron Dust',
    description: 'Use steam power to grind an iron ingot into dust.',
    tier: 'steam',
    machineId: 'steamMacerator',
    durationMs: 6000,
    steamCostLitres: 48,
    input: { id: 'ironIngot', amount: 1 },
    output: { id: 'ironDust', amount: 1 },
  },
  {
    id: 'steam_grind_copper_ingot',
    name: 'Steam Grind Copper Dust',
    description: 'Use steam power to grind a copper ingot into dust.',
    tier: 'steam',
    machineId: 'steamMacerator',
    durationMs: 6000,
    steamCostLitres: 48,
    input: { id: 'copperIngot', amount: 1 },
    output: { id: 'copperDust', amount: 1 },
  },
  {
    id: 'steam_grind_tin_ingot',
    name: 'Steam Grind Tin Dust',
    description: 'Use steam power to grind a tin ingot into dust.',
    tier: 'steam',
    machineId: 'steamMacerator',
    durationMs: 6000,
    steamCostLitres: 48,
    input: { id: 'tinIngot', amount: 1 },
    output: { id: 'tinDust', amount: 1 },
  },
  {
    id: 'steam_pulp_planks',
    name: 'Steam Pulp Planks',
    description: 'Macerate planks into fine wood pulp for coated boards.',
    tier: 'steam',
    machineId: 'steamMacerator',
    durationMs: 5000,
    steamCostLitres: 16,
    input: { id: 'plank', amount: 1 },
    output: { id: 'woodPulp', amount: 2 },
  },
  {
    id: 'steam_grind_carbon_dust',
    name: 'Steam Grind Carbon Dust',
    description: 'Macerate coal into carbon dust for resistor work.',
    tier: 'steam',
    machineId: 'steamMacerator',
    durationMs: 5000,
    steamCostLitres: 16,
    input: { id: 'coal', amount: 1 },
    output: { id: 'carbonDust', amount: 1 },
  },
  {
    id: 'coke_log',
    name: 'Coke Logs',
    description: 'Bake logs into charcoal and collect a small creosote trickle.',
    tier: 'steam',
    machineId: 'cokeOven',
    durationMs: 45000,
    input: { id: 'log', amount: 1 },
    output: { id: 'charcoal', amount: 1 },
    fluidOutput: { id: 'creosote', amount: 16 },
  },
  {
    id: 'coke_coal',
    name: 'Coke Coal',
    description: 'Bake coal into coal coke and collect creosote for the first fluid work.',
    tier: 'steam',
    machineId: 'cokeOven',
    durationMs: 60000,
    input: { id: 'coal', amount: 1 },
    output: { id: 'coalCoke', amount: 1 },
    fluidOutput: { id: 'creosote', amount: 32 },
  },
  {
    id: 'steam_hammer_iron_plate',
    name: 'Steam Hammer Iron Plate',
    description: 'Hammer iron ingots into plates with steam power.',
    tier: 'steam',
    machineId: 'steamForgeHammer',
    durationMs: 5000,
    steamCostLitres: 16,
    input: { id: 'ironIngot', amount: 2 },
    output: { id: 'ironPlate', amount: 1 },
  },
  {
    id: 'steam_hammer_bronze_plate',
    name: 'Steam Hammer Bronze Plate',
    description: 'Hammer bronze ingots into plates with steam power.',
    tier: 'steam',
    machineId: 'steamForgeHammer',
    durationMs: 5000,
    steamCostLitres: 16,
    input: { id: 'bronzeIngot', amount: 2 },
    output: { id: 'bronzePlate', amount: 1 },
  },
  {
    id: 'steam_hammer_steel_plate',
    name: 'Steam Hammer Steel Plate',
    description: 'Hammer steel ingots into plates for the first post-steel builds.',
    tier: 'steam',
    machineId: 'steamForgeHammer',
    durationMs: 6000,
    steamCostLitres: 24,
    input: { id: 'steelIngot', amount: 2 },
    output: { id: 'steelPlate', amount: 1 },
  },
  {
    id: 'steam_compress_firebrick',
    name: 'Steam Compress Firebrick',
    description: 'Compress firebrick feed into denser refractory blocks.',
    tier: 'steam',
    machineId: 'steamCompressor',
    durationMs: 5000,
    steamCostLitres: 16,
    input: { id: 'firebrick', amount: 2 },
    output: { id: 'cokeOvenBrick', amount: 1 },
  },
  {
    id: 'steam_extract_rubber',
    name: 'Steam Extract Rubber',
    description: 'Extract useful rubber from sticky resin.',
    tier: 'steam',
    machineId: 'steamExtractor',
    durationMs: 5000,
    steamCostLitres: 16,
    input: { id: 'rubberSap', amount: 1 },
    output: { id: 'rubber', amount: 1 },
  },
  {
    id: 'steam_alloy_bronze',
    name: 'Steam Alloy Bronze Dust',
    description: 'Alloy copper dust and tin dust directly into bronze ingots.',
    tier: 'steam',
    machineId: 'steamAlloySmelter',
    durationMs: 7000,
    steamCostLitres: 24,
    input: { id: 'copperDust', amount: 2 },
    secondaryInput: { id: 'tinDust', amount: 1 },
    output: { id: 'bronzeIngot', amount: 3 },
  },
  {
    id: 'steam_alloy_bronze_ingots',
    name: 'Steam Alloy Bronze Ingots',
    description: 'Alloy copper and tin ingots directly into bronze ingots.',
    tier: 'steam',
    machineId: 'steamAlloySmelter',
    durationMs: 7000,
    steamCostLitres: 24,
    input: { id: 'copperIngot', amount: 2 },
    secondaryInput: { id: 'tinIngot', amount: 1 },
    output: { id: 'bronzeIngot', amount: 3 },
  },
  {
    id: 'steam_alloy_red_alloy',
    name: 'Steam Alloy Red Alloy',
    description: 'Alloy copper dust and redstone dust into the first red alloy ingot.',
    tier: 'steam',
    machineId: 'steamAlloySmelter',
    durationMs: 9000,
    steamCostLitres: 32,
    input: { id: 'copperDust', amount: 1 },
    secondaryInput: { id: 'redstoneDust', amount: 4 },
    output: { id: 'redAlloyIngot', amount: 1 },
  },
  {
    id: 'smelt_glass',
    name: 'Smelt Glass',
    description: 'Fuse silica sand into rough glass panes.',
    tier: 'steam',
    machineId: 'furnace',
    durationMs: 10000,
    input: { id: 'sand', amount: 1 },
    output: { id: 'glass', amount: 1 },
  },
  {
    id: 'steam_furnace_iron',
    name: 'Steam Furnace Iron',
    description: 'Smelt iron ore in a faster steam furnace.',
    tier: 'steam',
    machineId: 'steamFurnace',
    durationMs: 6500,
    steamCostLitres: 16,
    input: { id: 'ironOre', amount: 1 },
    output: { id: 'ironIngot', amount: 1 },
  },
  {
    id: 'steam_furnace_glass',
    name: 'Steam Furnace Glass',
    description: 'Fuse silica sand into glass with steam heat.',
    tier: 'steam',
    machineId: 'steamFurnace',
    durationMs: 5000,
    steamCostLitres: 16,
    input: { id: 'sand', amount: 1 },
    output: { id: 'glass', amount: 1 },
  },
  {
    id: 'steel_from_coal_coke',
    name: 'Blast Steel With Coal Coke',
    description: 'Coal coke drives the fastest early one-ingot steel heat.',
    tier: 'steam',
    machineId: 'brickedBlastFurnace',
    durationMs: 25000,
    input: { id: 'ironIngot', amount: 1 },
    fuelInput: { id: 'coalCoke', amount: 1 },
    output: { id: 'steelIngot', amount: 1 },
  },
  {
    id: 'steel_from_coal',
    name: 'Blast Steel With Coal',
    description: 'Coal can run the blast furnace, but it sits between charcoal and coal coke.',
    tier: 'steam',
    machineId: 'brickedBlastFurnace',
    durationMs: 35000,
    input: { id: 'ironIngot', amount: 1 },
    fuelInput: { id: 'coal', amount: 1 },
    output: { id: 'steelIngot', amount: 1 },
  },
  {
    id: 'steel_from_charcoal',
    name: 'Blast Steel With Charcoal',
    description: 'Charcoal can make first steel, but each ingot takes longer.',
    tier: 'steam',
    machineId: 'brickedBlastFurnace',
    durationMs: 40000,
    input: { id: 'ironIngot', amount: 1 },
    fuelInput: { id: 'charcoal', amount: 1 },
    output: { id: 'steelIngot', amount: 1 },
  },
]

export const questChapters: QuestChapter[] = [
  {
    id: 'gettingStarted',
    title: 'Getting Started',
    description: 'Punch wood, shape the first tools, and unlock stone gathering.',
  },
  {
    id: 'stoneAndFire',
    title: 'Stone & Fire',
    description: 'Build the first furnace, make brick, and prepare the factory floor.',
  },
  {
    id: 'steamAge',
    title: 'Steam Age',
    description: 'Turn water and fuel into steam, then feed the first machines.',
  },
  {
    id: 'cokeAndSteel',
    title: 'Coke & Steel',
    description: 'Make coke oven products, assemble the BBF, and produce the first steel.',
  },
  {
    id: 'lvFoundations',
    title: 'LV Foundations',
    description: 'Make red alloy, rubber wiring, vacuum tubes, and the first basic circuit.',
  },
]

export const quests: Quest[] = [
  {
    id: 'punchTree',
    chapterId: 'gettingStarted',
    chapter: 'Getting Started',
    title: 'Punch a log loose',
    description: 'Damage the tree until one full log drops into your inventory.',
    position: { x: 40, y: 120 },
    icon: { type: 'gather', id: 'tree' },
    requirements: {
      resources: [{ id: 'log', amount: 1 }],
    },
    rewards: {},
  },
  {
    id: 'craftPlanks',
    chapterId: 'gettingStarted',
    chapter: 'Getting Started',
    title: 'Split logs into planks',
    description: 'Turn rough logs into useful boards.',
    position: { x: 210, y: 120 },
    icon: { type: 'resource', id: 'plank' },
    prerequisites: ['punchTree'],
    requirements: {
      resources: [{ id: 'plank', amount: 4 }],
    },
    rewards: {},
  },
  {
    id: 'craftSticks',
    chapterId: 'gettingStarted',
    chapter: 'Getting Started',
    title: 'Carve sticks',
    description: 'Tools need handles before they can become helpful.',
    position: { x: 380, y: 120 },
    icon: { type: 'resource', id: 'stick' },
    prerequisites: ['craftPlanks'],
    requirements: {
      resources: [{ id: 'stick', amount: 4 }],
    },
    rewards: {},
  },
  {
    id: 'craftAxe',
    chapterId: 'gettingStarted',
    chapter: 'Getting Started',
    title: 'Make a wooden axe',
    description: 'Three planks and two sticks become your first speed upgrade.',
    position: { x: 640, y: 40 },
    icon: { type: 'resource', id: 'woodenAxe' },
    prerequisites: ['craftSticks'],
    requirements: {
      resources: [{ id: 'woodenAxe', amount: 1 }],
    },
    rewards: {},
  },
  {
    id: 'chopFaster',
    chapterId: 'gettingStarted',
    chapter: 'Getting Started',
    title: 'Chop with the axe',
    description: 'Use the wooden axe to break a second log faster.',
    position: { x: 850, y: 40 },
    icon: { type: 'resource', id: 'log' },
    prerequisites: ['craftAxe'],
    requirements: {
      resources: [{ id: 'log', amount: 8 }],
    },
    rewards: {},
  },
  {
    id: 'mineStone',
    chapterId: 'gettingStarted',
    chapter: 'Getting Started',
    title: 'Crack into stone',
    description: 'Make a wooden pickaxe and mine enough cobblestone for the first furnace shell.',
    position: { x: 640, y: 230 },
    icon: { type: 'gather', id: 'stone' },
    prerequisites: ['craftSticks'],
    requirements: {
      resources: [
        { id: 'woodenPickaxe', amount: 1 },
        { id: 'cobblestone', amount: 8 },
      ],
    },
    rewards: {},
  },
  {
    id: 'buildFurnace',
    chapterId: 'stoneAndFire',
    chapter: 'Stone & Fire',
    title: 'Build a primitive furnace',
    description: 'Shape a cobblestone ring and place the first heat source.',
    position: { x: 70, y: 140 },
    icon: { type: 'machine', id: 'furnace' },
    prerequisites: ['mineStone'],
    requirements: {
      machines: [{ id: 'furnace', amount: 1 }],
    },
    rewards: {},
  },
  {
    id: 'craftMortar',
    chapterId: 'stoneAndFire',
    chapter: 'Stone & Fire',
    title: 'Make a pestle and mortar',
    description: 'A mortar opens the dusty, awkward side of early processing.',
    position: { x: 250, y: 70 },
    icon: { type: 'resource', id: 'mortar' },
    prerequisites: ['mineStone'],
    requirements: {
      resources: [{ id: 'mortar', amount: 1 }],
    },
    rewards: {},
  },
  {
    id: 'firstDirt',
    chapterId: 'stoneAndFire',
    chapter: 'Stone & Fire',
    title: 'Forge an iron pickaxe',
    description: 'Stone tools open iron. Smelt it, then make the pick that can bite into copper and tin.',
    position: { x: 430, y: 140 },
    icon: { type: 'resource', id: 'ironPickaxe' },
    prerequisites: ['buildFurnace', 'craftMortar'],
    requirements: {
      resources: [{ id: 'ironPickaxe', amount: 1 }],
      machines: [{ id: 'furnace', amount: 1 }],
    },
    rewards: {},
  },
  {
    id: 'copperAndTin',
    chapterId: 'stoneAndFire',
    chapter: 'Stone & Fire',
    title: 'Find the soft metals',
    description: 'Copper and tin unlock the first real progression knot.',
    position: { x: 610, y: 140 },
    icon: { type: 'gather', id: 'copperVein' },
    prerequisites: ['firstDirt'],
    requirements: {
      resources: [
        { id: 'copperOre', amount: 12 },
        { id: 'tinOre', amount: 6 },
      ],
    },
    rewards: {},
  },
  {
    id: 'bronzeAge',
    chapterId: 'stoneAndFire',
    chapter: 'Stone & Fire',
    title: 'Mix the first bronze dust',
    description: 'Grind copper and tin, then mix them into the first bronze batch.',
    position: { x: 790, y: 140 },
    icon: { type: 'resource', id: 'bronzeBlend' },
    prerequisites: ['copperAndTin'],
    requirements: {
      resources: [{ id: 'bronzeBlend', amount: 4 }],
      machines: [{ id: 'furnace', amount: 1 }],
    },
    rewards: {},
  },
  {
    id: 'gatherClay',
    chapterId: 'stoneAndFire',
    chapter: 'Stone & Fire',
    title: 'Dig clay and sand',
    description: 'Shovels open the lake edge materials needed for bricks and coke ovens.',
    position: { x: 430, y: 290 },
    icon: { type: 'gather', id: 'clayPatch' },
    prerequisites: ['firstDirt'],
    requirements: {
      resources: [
        { id: 'clay', amount: 16 },
        { id: 'sand', amount: 8 },
      ],
    },
    rewards: {},
  },
  {
    id: 'makeBricks',
    chapterId: 'stoneAndFire',
    chapter: 'Stone & Fire',
    title: 'Fire the first bricks',
    description: 'Clay bricks become the backbone of early water and coke processing.',
    position: { x: 610, y: 290 },
    icon: { type: 'resource', id: 'brick' },
    prerequisites: ['gatherClay', 'buildFurnace'],
    requirements: {
      resources: [{ id: 'brick', amount: 16 }],
    },
    rewards: {},
  },
  {
    id: 'buildFoundation',
    chapterId: 'stoneAndFire',
    chapter: 'Stone & Fire',
    title: 'Lay factory foundations',
    description: 'Build the first 5x5 factory floor so machines can be placed properly.',
    position: { x: 790, y: 290 },
    icon: { type: 'machine', id: 'furnace' },
    prerequisites: ['makeBricks'],
    objectives: [{ type: 'factoryFoundation', level: 1, label: 'Factory floor 5x5 unlocked' }],
    requirements: {},
    rewards: {},
  },
  {
    id: 'buildWell',
    chapterId: 'steamAge',
    chapter: 'Steam Age',
    title: 'Build a well',
    description: 'A reliable water source can keep up with a small cluster of boilers.',
    position: { x: 70, y: 140 },
    icon: { type: 'machine', id: 'well' },
    prerequisites: ['buildFoundation', 'bronzeAge'],
    requirements: {
      machines: [{ id: 'well', amount: 1 }],
    },
    rewards: {},
  },
  {
    id: 'makeSteam',
    chapterId: 'steamAge',
    chapter: 'Steam Age',
    title: 'Make steam',
    description: 'Place a boiler by water, feed it fuel, and start the awkward steam era.',
    position: { x: 250, y: 140 },
    icon: { type: 'machine', id: 'steamBoiler' },
    prerequisites: ['buildWell'],
    objectives: [
      { type: 'machine', id: 'steamBoiler', amount: 1 },
      { type: 'placedMachine', id: 'steamBoiler', amount: 1, label: 'Steam boiler placed' },
    ],
    requirements: {
      machines: [{ id: 'steamBoiler', amount: 1 }],
    },
    rewards: {},
  },
  {
    id: 'pipeSteam',
    chapterId: 'steamAge',
    chapter: 'Steam Age',
    title: 'Route steam into storage',
    description: 'Tanks and pipes turn single-machine steam into a small factory network.',
    position: { x: 430, y: 140 },
    icon: { type: 'machine', id: 'steamTank' },
    prerequisites: ['makeSteam'],
    requirements: {
      machines: [
        { id: 'steamTank', amount: 1 },
        { id: 'copperPipe', amount: 4 },
      ],
    },
    rewards: {},
  },
  {
    id: 'steamMaceratorQuest',
    chapterId: 'steamAge',
    chapter: 'Steam Age',
    title: 'Install a steam macerator',
    description: 'The macerator makes ore processing more deliberate and more productive.',
    position: { x: 610, y: 60 },
    icon: { type: 'machine', id: 'steamMacerator' },
    prerequisites: ['pipeSteam'],
    requirements: {
      machines: [{ id: 'steamMacerator', amount: 1 }],
    },
    rewards: {},
  },
  {
    id: 'steamForgeHammerQuest',
    chapterId: 'steamAge',
    chapter: 'Steam Age',
    title: 'Add a forge hammer',
    description: 'Steam hammering takes some pressure off the hand-tool grind.',
    position: { x: 610, y: 220 },
    icon: { type: 'machine', id: 'steamForgeHammer' },
    prerequisites: ['pipeSteam'],
    requirements: {
      machines: [{ id: 'steamForgeHammer', amount: 1 }],
    },
    rewards: {},
  },
  {
    id: 'steamUtilityBranch',
    chapterId: 'steamAge',
    chapter: 'Steam Age',
    title: 'Broaden the steam line',
    description: 'Compressor, extractor, alloy smelter, and steam furnace become the workshop backbone.',
    position: { x: 790, y: 140 },
    icon: { type: 'machine', id: 'steamAlloySmelter' },
    prerequisites: ['steamMaceratorQuest', 'steamForgeHammerQuest'],
    requirements: {
      machines: [
        { id: 'steamCompressor', amount: 1 },
        { id: 'steamExtractor', amount: 1 },
        { id: 'steamAlloySmelter', amount: 1 },
        { id: 'steamFurnace', amount: 1 },
      ],
    },
    rewards: {},
  },
  {
    id: 'treeTapQuest',
    chapterId: 'cokeAndSteel',
    chapter: 'Coke & Steel',
    title: 'Tap sticky resin',
    description: 'Rubber trees and resin start the first fluid-adjacent crafting chain.',
    position: { x: 70, y: 80 },
    icon: { type: 'resource', id: 'rubberSap' },
    prerequisites: ['buildFoundation'],
    requirements: {
      resources: [
        { id: 'treeTap', amount: 1 },
        { id: 'rubberSap', amount: 4 },
      ],
    },
    rewards: {},
  },
  {
    id: 'cokeOvenQuest',
    chapterId: 'cokeAndSteel',
    chapter: 'Coke & Steel',
    title: 'Build the coke oven',
    description: 'Coke ovens produce charcoal, coal coke, and the creosote chain.',
    position: { x: 250, y: 140 },
    icon: { type: 'machine', id: 'cokeOven' },
    prerequisites: ['treeTapQuest', 'makeBricks'],
    requirements: {
      machines: [{ id: 'cokeOven', amount: 1 }],
    },
    rewards: {},
  },
  {
    id: 'creosoteQuest',
    chapterId: 'cokeAndSteel',
    chapter: 'Coke & Steel',
    title: 'Cook the first coke',
    description: 'Run the coke oven until coal coke appears and creosote starts moving through the system.',
    position: { x: 430, y: 140 },
    icon: { type: 'resource', id: 'coalCoke' },
    prerequisites: ['cokeOvenQuest'],
    requirements: {
      resources: [{ id: 'coalCoke', amount: 1 }],
    },
    rewards: {},
  },
  {
    id: 'bbfCasingsQuest',
    chapterId: 'cokeAndSteel',
    chapter: 'Coke & Steel',
    title: 'Craft BBF casings',
    description: 'Firebrick and iron plate become the pieces of the first blast furnace multiblock.',
    position: { x: 610, y: 80 },
    icon: { type: 'resource', id: 'bbfCasing' },
    prerequisites: ['creosoteQuest'],
    requirements: {
      resources: [{ id: 'bbfCasing', amount: 4 }],
    },
    rewards: {},
  },
  {
    id: 'buildBbfQuest',
    chapterId: 'cokeAndSteel',
    chapter: 'Coke & Steel',
    title: 'Form the BBF multiblock',
    description: 'Place the casings as a 2x2 on the factory floor to form the bricked blast furnace.',
    position: { x: 790, y: 80 },
    icon: { type: 'machine', id: 'brickedBlastFurnace' },
    prerequisites: ['bbfCasingsQuest'],
    requirements: {
      machines: [{ id: 'brickedBlastFurnace', amount: 1 }],
    },
    rewards: {},
  },
  {
    id: 'firstSteel',
    chapterId: 'cokeAndSteel',
    chapter: 'Coke & Steel',
    title: 'Blast the first steel',
    description: 'Iron plus real furnace fuel becomes the first steel ingot.',
    position: { x: 970, y: 80 },
    icon: { type: 'resource', id: 'steelIngot' },
    prerequisites: ['buildBbfQuest'],
    requirements: {
      resources: [{ id: 'steelIngot', amount: 1 }],
    },
    rewards: {},
  },
  {
    id: 'steelPlateQuest',
    chapterId: 'cokeAndSteel',
    chapter: 'Coke & Steel',
    title: 'Plate the steel',
    description: 'Hammer the first steel plate and step onto the edge of the next technology tier.',
    position: { x: 1150, y: 80 },
    icon: { type: 'resource', id: 'steelPlate' },
    prerequisites: ['firstSteel'],
    requirements: {
      resources: [{ id: 'steelPlate', amount: 1 }],
    },
    rewards: {},
  },
  {
    id: 'findRedstone',
    chapterId: 'lvFoundations',
    chapter: 'LV Foundations',
    title: 'Find redstone',
    description: 'Mine the first redstone dust so copper can become signal metal.',
    position: { x: 70, y: 140 },
    icon: { type: 'gather', id: 'redstoneVein' },
    prerequisites: ['steelPlateQuest', 'steamUtilityBranch'],
    requirements: {
      resources: [{ id: 'redstoneDust', amount: 4 }],
    },
    rewards: {},
  },
  {
    id: 'smeltRedAlloy',
    chapterId: 'lvFoundations',
    chapter: 'LV Foundations',
    title: 'Smelt red alloy',
    description: 'Run copper dust and redstone dust through the alloy smelter.',
    position: { x: 250, y: 140 },
    icon: { type: 'resource', id: 'redAlloyIngot' },
    prerequisites: ['findRedstone'],
    requirements: {
      resources: [{ id: 'redAlloyIngot', amount: 1 }],
    },
    rewards: {},
  },
  {
    id: 'extractRubberQuest',
    chapterId: 'lvFoundations',
    chapter: 'LV Foundations',
    title: 'Extract rubber',
    description: 'Steam-extract sticky resin into rubber for insulated wiring.',
    position: { x: 430, y: 60 },
    icon: { type: 'resource', id: 'rubber' },
    prerequisites: ['smeltRedAlloy'],
    requirements: {
      resources: [{ id: 'rubber', amount: 2 }],
    },
    rewards: {},
  },
  {
    id: 'insulateWireQuest',
    chapterId: 'lvFoundations',
    chapter: 'LV Foundations',
    title: 'Insulate copper wire',
    description: 'Draw copper wire and wrap it in rubber.',
    position: { x: 610, y: 60 },
    icon: { type: 'resource', id: 'conductiveWire' },
    prerequisites: ['extractRubberQuest'],
    requirements: {
      resources: [{ id: 'conductiveWire', amount: 2 }],
    },
    rewards: {},
  },
  {
    id: 'makeGlassTubes',
    chapterId: 'lvFoundations',
    chapter: 'LV Foundations',
    title: 'Make glass tubes',
    description: 'Smelt sand into glass and file it into fragile tubes.',
    position: { x: 430, y: 220 },
    icon: { type: 'resource', id: 'glassTube' },
    prerequisites: ['smeltRedAlloy'],
    requirements: {
      resources: [{ id: 'glassTube', amount: 2 }],
    },
    rewards: {},
  },
  {
    id: 'makeResistors',
    chapterId: 'lvFoundations',
    chapter: 'LV Foundations',
    title: 'Make resistors',
    description: 'Carbon dust and copper wire become the first crude electronic parts.',
    position: { x: 610, y: 220 },
    icon: { type: 'resource', id: 'resistor' },
    prerequisites: ['makeGlassTubes'],
    requirements: {
      resources: [{ id: 'resistor', amount: 2 }],
    },
    rewards: {},
  },
  {
    id: 'makeVacuumTubes',
    chapterId: 'lvFoundations',
    chapter: 'LV Foundations',
    title: 'Build vacuum tubes',
    description: 'Use glass, red alloy wire, copper wire, and steel rods to make valves.',
    position: { x: 790, y: 140 },
    icon: { type: 'resource', id: 'vacuumTube' },
    prerequisites: ['insulateWireQuest', 'makeResistors'],
    requirements: {
      resources: [{ id: 'vacuumTube', amount: 2 }],
    },
    rewards: {},
  },
  {
    id: 'pressCircuitBoard',
    chapterId: 'lvFoundations',
    chapter: 'LV Foundations',
    title: 'Coat a circuit board',
    description: 'Wood pulp, rubber, and copper wire become the first board substrate.',
    position: { x: 970, y: 60 },
    icon: { type: 'resource', id: 'basicBoard' },
    prerequisites: ['makeVacuumTubes'],
    requirements: {
      resources: [{ id: 'basicBoard', amount: 1 }],
    },
    rewards: {},
  },
  {
    id: 'firstLvCircuit',
    chapterId: 'lvFoundations',
    chapter: 'LV Foundations',
    title: 'Assemble the first LV circuit',
    description: 'Bring the board, wire, resistors, tubes, redstone, and steel plate together.',
    position: { x: 1150, y: 140 },
    icon: { type: 'resource', id: 'primitiveCircuit' },
    prerequisites: ['pressCircuitBoard'],
    requirements: {
      resources: [{ id: 'primitiveCircuit', amount: 1 }],
    },
    rewards: {},
  },
]

export const initialResources: Record<ResourceId, number> = Object.keys(resourceLabels).reduce(
  (resources, id) => ({ ...resources, [id]: 0 }),
  {} as Record<ResourceId, number>,
)

export const initialMachines: Record<MachineId, number> = Object.keys(machines).reduce(
  (builtMachines, id) => ({ ...builtMachines, [id]: 0 }),
  {} as Record<MachineId, number>,
)

export const initialEquipment: EquipmentState = {
  helmet: null,
  chestplate: null,
  leggings: null,
  boots: null,
  axe: null,
  shovel: null,
  pickaxe: null,
  weapon: null,
}

export function createInitialState(now = Date.now()): GameState {
  return {
    version: 1,
    resources: { ...initialResources },
    machines: { ...initialMachines },
    machineInstances: [],
    factoryFoundationLevel: 0,
    completedQuests: [],
    claimedQuests: [],
    unlockedQuests: ['punchTree'],
    craftedResources: [],
    equipment: { ...initialEquipment },
    durability: {},
    gatherProgress: {},
    machineProgress: {},
    lastSavedAt: now,
  }
}
