export const materialFamilies = [
  {
    id: 'iron',
    label: 'Iron',
    tier: 'bronze',
    forms: {
      ingot: 'ironIngot',
      dust: 'ironDust',
      plate: 'ironPlate',
      rod: 'ironRod',
      bolt: 'ironBolt',
      ring: 'ironRing',
      screw: 'ironScrew',
      gear: 'ironGear',
      wire: 'ironWire',
      fineWire: 'fineIronWire',
      foil: 'ironFoil',
    },
  },
  {
    id: 'copper',
    label: 'Copper',
    tier: 'bronze',
    forms: {
      ingot: 'copperIngot',
      dust: 'copperDust',
      plate: 'copperPlate',
      rod: 'copperRod',
      bolt: 'copperBolt',
      ring: 'copperRing',
      screw: 'copperScrew',
      gear: 'copperGear',
      wire: 'copperWire',
      fineWire: 'fineCopperWire',
      foil: 'copperFoil',
    },
  },
  {
    id: 'tin',
    label: 'Tin',
    tier: 'bronze',
    forms: {
      ingot: 'tinIngot',
      dust: 'tinDust',
      plate: 'tinPlate',
      rod: 'tinRod',
      bolt: 'tinBolt',
      ring: 'tinRing',
      screw: 'tinScrew',
      gear: 'tinGear',
      wire: 'tinWire',
      fineWire: 'fineTinWire',
      foil: 'tinFoil',
    },
  },
  {
    id: 'bronze',
    label: 'Bronze',
    tier: 'bronze',
    forms: {
      ingot: 'bronzeIngot',
      dust: 'bronzeBlend',
      plate: 'bronzePlate',
      rod: 'bronzeRod',
      bolt: 'bronzeBolt',
      ring: 'bronzeRing',
      screw: 'bronzeScrew',
      gear: 'bronzeGear',
      wire: 'bronzeWire',
      fineWire: 'fineBronzeWire',
      foil: 'bronzeFoil',
    },
  },
  {
    id: 'nickel',
    label: 'Nickel',
    tier: 'lv',
    forms: {
      ingot: 'nickelIngot',
      dust: 'nickelDust',
      plate: 'nickelPlate',
      rod: 'nickelRod',
      bolt: 'nickelBolt',
      ring: 'nickelRing',
      screw: 'nickelScrew',
      gear: 'nickelGear',
      wire: 'nickelWire',
      fineWire: 'fineNickelWire',
      foil: 'nickelFoil',
    },
  },
  {
    id: 'cupronickel',
    label: 'Cupronickel',
    tier: 'lv',
    forms: {
      ingot: 'cupronickelIngot',
      dust: 'cupronickelDust',
      plate: 'cupronickelPlate',
      rod: 'cupronickelRod',
      bolt: 'cupronickelBolt',
      ring: 'cupronickelRing',
      screw: 'cupronickelScrew',
      gear: 'cupronickelGear',
      wire: 'cupronickelWire',
      fineWire: 'fineCupronickelWire',
      foil: 'cupronickelFoil',
    },
  },
  {
    id: 'invar',
    label: 'Invar',
    tier: 'lv',
    forms: {
      ingot: 'invarIngot',
      dust: 'invarDust',
      plate: 'invarPlate',
      rod: 'invarRod',
      bolt: 'invarBolt',
      ring: 'invarRing',
      screw: 'invarScrew',
      gear: 'invarGear',
      wire: 'invarWire',
      fineWire: 'fineInvarWire',
      foil: 'invarFoil',
    },
  },
  {
    id: 'aluminium',
    label: 'Aluminium',
    tier: 'lv',
    forms: {
      ingot: 'aluminiumIngot',
      dust: 'aluminiumDust',
      plate: 'aluminiumPlate',
      rod: 'aluminiumRod',
      bolt: 'aluminiumBolt',
      ring: 'aluminiumRing',
      screw: 'aluminiumScrew',
      gear: 'aluminiumGear',
      wire: 'aluminiumWire',
      fineWire: 'fineAluminiumWire',
      foil: 'aluminiumFoil',
    },
  },
  {
    id: 'gold',
    label: 'Gold',
    tier: 'mv',
    forms: {
      ingot: 'goldIngot',
      dust: 'goldDust',
      plate: 'goldPlate',
      rod: 'goldRod',
      bolt: 'goldBolt',
      ring: 'goldRing',
      screw: 'goldScrew',
      gear: 'goldGear',
      wire: 'goldWire',
      fineWire: 'fineGoldWire',
      foil: 'goldFoil',
    },
  },
  {
    id: 'steel',
    label: 'Steel',
    tier: 'steam',
    forms: {
      ingot: 'steelIngot',
      dust: 'steelDust',
      plate: 'steelPlate',
      rod: 'steelRod',
      bolt: 'steelBolt',
      ring: 'steelRing',
      screw: 'steelScrew',
      gear: 'steelGear',
      wire: 'steelWire',
      fineWire: 'fineSteelWire',
      foil: 'steelFoil',
    },
  },
  {
    id: 'redAlloy',
    label: 'Red Alloy',
    tier: 'steam',
    forms: {
      ingot: 'redAlloyIngot',
      dust: 'redAlloyDust',
      plate: 'redAlloyPlate',
      rod: 'redAlloyRod',
      bolt: 'redAlloyBolt',
      ring: 'redAlloyRing',
      screw: 'redAlloyScrew',
      gear: 'redAlloyGear',
      wire: 'redAlloyWire',
      fineWire: 'fineRedAlloyWire',
      foil: 'redAlloyFoil',
    },
  },
  {
    id: 'lead',
    label: 'Lead',
    tier: 'lv',
    forms: {
      ingot: 'leadIngot',
      dust: 'leadDust',
      plate: 'leadPlate',
      rod: 'leadRod',
      bolt: 'leadBolt',
      ring: 'leadRing',
      screw: 'leadScrew',
      gear: 'leadGear',
      wire: 'leadWire',
      fineWire: 'fineLeadWire',
      foil: 'leadFoil',
    },
  },
  {
    id: 'batteryAlloy',
    label: 'Battery Alloy',
    tier: 'lv',
    forms: {
      ingot: 'batteryAlloyIngot',
      dust: 'batteryAlloyDust',
      plate: 'batteryAlloyPlate',
      rod: 'batteryAlloyRod',
      bolt: 'batteryAlloyBolt',
      ring: 'batteryAlloyRing',
      screw: 'batteryAlloyScrew',
      gear: 'batteryAlloyGear',
      wire: 'batteryAlloyWire',
      fineWire: 'fineBatteryAlloyWire',
      foil: 'batteryAlloyFoil',
    },
  },
] as const

export type MaterialFamily = (typeof materialFamilies)[number]
export type MaterialFamilyId = MaterialFamily['id']
export type MaterialFormId = keyof MaterialFamily['forms']
export type MaterialResourceId = MaterialFamily['forms'][MaterialFormId]

export const materialResourceIds = materialFamilies.flatMap((family) => Object.values(family.forms)) as MaterialResourceId[]
