import type { MachineId, MachineSpec, ProcessRecipe, Recipe, ResourceId, ResourceSpec } from './types'
import type { MvMachineId, MvResourceId } from './mvIds'
import { materialFamilies } from './materialIds'

const resource = (
  id: MvResourceId,
  label: string,
  category: ResourceSpec['category'],
  tier: ResourceSpec['tier'] = 'mv',
): ResourceSpec => ({ id, label, category, tier, sortGroup: 'mv-engineering' })

export const mvResourceRegistry: Record<MvResourceId, ResourceSpec> = {
  sphaleriteOre: resource('sphaleriteOre', 'Sphalerite Ore', 'raw'),
  realgarOre: resource('realgarOre', 'Realgar Ore', 'raw'),
  sphaleriteConcentrate: resource('sphaleriteConcentrate', 'Gallium-bearing Sphalerite Concentrate', 'dust'),
  zincDust: resource('zincDust', 'Zinc Dust', 'dust'),
  arsenicDust: resource('arsenicDust', 'Arsenic Dust', 'dust'),
  galliumDust: resource('galliumDust', 'Gallium Dust', 'dust'),
  galliumArsenideCrystal: resource('galliumArsenideCrystal', 'Gallium Arsenide Crystal', 'component'),
  galliumArsenideDust: resource('galliumArsenideDust', 'Gallium Arsenide Dust', 'dust'),
  phenolicBoard: resource('phenolicBoard', 'Phenolic Board', 'circuit'),
  mvCircuitBoard: resource('mvCircuitBoard', 'MV Circuit Board', 'circuit'),
  diode: resource('diode', 'Diode', 'circuit'),
  mvCircuit: resource('mvCircuit', 'Good Electronic Circuit', 'circuit'),
  mvMachineCasing: resource('mvMachineCasing', 'MV Machine Casing', 'machinePart'),
  mvMachineHull: resource('mvMachineHull', 'MV Machine Hull', 'machinePart'),
  magneticSteelRod: resource('magneticSteelRod', 'Magnetic Steel Rod', 'component'),
  bronzeRotor: resource('bronzeRotor', 'Bronze Rotor', 'component'),
  steelPipeSection: resource('steelPipeSection', 'Steel Pipe Section', 'component'),
  mvMotor: resource('mvMotor', 'MV Motor', 'component'),
  mvPiston: resource('mvPiston', 'MV Piston', 'component'),
  mvPump: resource('mvPump', 'MV Pump', 'component'),
  mvConveyor: resource('mvConveyor', 'MV Conveyor', 'component'),
  emptyMvBatteryHull: resource('emptyMvBatteryHull', 'Empty MV Battery Hull', 'component'),
  mvLithiumBattery: resource('mvLithiumBattery', 'MV Lithium Battery', 'component'),
  aluminiumCable2A: resource('aluminiumCable2A', '2A Aluminium Cable', 'wire'),
  aluminiumCable4A: resource('aluminiumCable4A', '4A Aluminium Cable', 'wire'),
  aluminiumCable8A: resource('aluminiumCable8A', '8A Aluminium Cable', 'wire'),
  extrusionMoldPlate: resource('extrusionMoldPlate', 'Extrusion Mold (Plate)', 'tool'),
  extrusionMoldRod: resource('extrusionMoldRod', 'Extrusion Mold (Rod)', 'tool'),
  extrusionMoldBolt: resource('extrusionMoldBolt', 'Extrusion Mold (Bolt)', 'tool'),
  extrusionMoldRing: resource('extrusionMoldRing', 'Extrusion Mold (Ring)', 'tool'),
  extrusionMoldGear: resource('extrusionMoldGear', 'Extrusion Mold (Gear)', 'tool'),
}

const mvProcessMachines = [
  ['mvMacerator', 'MV Macerator', 'Crushes LV and MV feedstock at MV speed.', 384],
  ['mvForgeHammer', 'MV Forge Hammer', 'Forms plates and dense parts at MV speed.', 384],
  ['mvCompressor', 'MV Compressor', 'Presses boards, casings, and advanced parts.', 384],
  ['mvExtractor', 'MV Extractor', 'Extracts useful fractions from advanced feedstock.', 384],
  ['mvAlloySmelter', 'MV Alloy Smelter', 'Runs established alloy recipes at MV speed.', 512],
  ['mvFurnace', 'MV Furnace', 'Smelts established furnace recipes at MV speed.', 384],
  ['mvWiremill', 'MV Wiremill', 'Draws wire, foil, and fine wire at MV speed.', 384],
  ['mvBender', 'MV Bender', 'Bends plates, foils, and casings at MV speed.', 384],
  ['mvLathe', 'MV Lathe', 'Turns rods, bolts, rings, and screws at MV speed.', 384],
  ['mvElectrolyzer', 'MV Electrolyzer', 'Separates mineral and chemical feedstocks.', 512],
  ['mvAssembler', 'MV Assembler', 'Assembles components and infrastructure at MV speed.', 512],
  ['mvMixer', 'MV Mixer', 'Mixes solid and fluid batches at MV speed.', 512],
  ['mvCentrifuge', 'MV Centrifuge', 'Separates item and fluid byproducts at MV speed.', 512],
  ['mvCanner', 'MV Canner', 'Fills and seals MV cells and batteries.', 512],
  ['mvAutoMiner', 'MV Auto Miner', 'Runs a faster electric mining head from an MV network.', 384],
  ['mvChemicalReactor', 'MV Chemical Reactor', 'Runs sealed reactions with MV throughput.', 512],
  ['mvAirCollector', 'MV Air Collector', 'Collects a full air batch at MV speed.', 384],
  ['mvDistillery', 'MV Distillery', 'Distils established fluid recipes at MV speed.', 512],
] as const

const fluidMachineBuffers: Partial<Record<MvMachineId, MachineSpec['fluidBuffers']>> = {
  mvAssembler: [{ id: 'input', label: 'Recipe fluid', capacityLitres: 256, access: 'input', fluidRule: 'recipe-inputs' }],
  mvMixer: [
    { id: 'feed-a', label: 'Fluid input 1', capacityLitres: 64, access: 'input', fluidRule: 'recipe-inputs' },
    { id: 'feed-b', label: 'Fluid input 2', capacityLitres: 64, access: 'input', fluidRule: 'recipe-inputs' },
    { id: 'product', label: 'Fluid output', capacityLitres: 64, access: 'output', fluidRule: 'recipe-outputs' },
  ],
  mvCentrifuge: [
    { id: 'feed', label: 'Fluid input', capacityLitres: 64, access: 'input', fluidRule: 'recipe-inputs' },
    { id: 'productA', label: 'Fluid output A', capacityLitres: 64, access: 'output', fluidRule: 'recipe-outputs' },
    { id: 'productB', label: 'Fluid output B', capacityLitres: 64, access: 'output', fluidRule: 'recipe-outputs' },
  ],
  mvChemicalReactor: [
    { id: 'feedA', label: 'Fluid input A', capacityLitres: 64, access: 'input', fluidRule: 'recipe-inputs' },
    { id: 'feedB', label: 'Fluid input B', capacityLitres: 64, access: 'input', fluidRule: 'recipe-inputs' },
    { id: 'reaction', label: 'Fluid output', capacityLitres: 64, access: 'output', fluidRule: 'recipe-outputs' },
  ],
  mvAirCollector: [{ id: 'output', label: 'Air output', capacityLitres: 64, access: 'output', fluidRule: ['air'] }],
  mvDistillery: [
    { id: 'feed', label: 'Distillation feed', capacityLitres: 128, access: 'input', fluidRule: 'recipe-inputs' },
    { id: 'benzene', label: 'Light fraction', capacityLitres: 128, access: 'output', fluidRule: 'recipe-outputs' },
    { id: 'residue', label: 'Heavy fraction', capacityLitres: 128, access: 'output', fluidRule: 'recipe-outputs' },
  ],
}

const generatedMvMachines = Object.fromEntries(mvProcessMachines.map(([id, name, description, euCapacity]) => [
  id,
  {
    id,
    name,
    description,
    tier: 'mv',
    placeable: true,
    processKind: 'euProcess',
    euCapacity,
    euVoltage: 128,
    ...(fluidMachineBuffers[id] ? {
      fluidCapacityLitres: Math.max(...fluidMachineBuffers[id]!.map((buffer) => buffer.capacityLitres)),
      fluidOutputLitresPerSecond: 48,
      fluidBuffers: fluidMachineBuffers[id],
    } : {}),
    ...((id === 'mvMacerator' || id === 'mvCentrifuge') ? { itemOutputSlots: 2 as const } : {}),
  },
])) as Record<(typeof mvProcessMachines)[number][0], MachineSpec>

const batteryBuffer = (id: MvMachineId, amps: number): MachineSpec => ({
  id,
  name: `${amps}A MV Battery Buffer`,
  description: `Stores up to ${amps} MV batteries and supplies ${amps * 128} EU/s through its output faces.`,
  tier: 'mv',
  placeable: true,
  processKind: 'euStorage',
  euAmps: amps,
  euVoltage: 128,
  euCapacity: amps * 16_384,
})

const cable = (id: MvMachineId, amps: number): MachineSpec => ({
  id,
  name: `${amps}A Aluminium Cable`,
  description: `Carries ${amps} amp${amps === 1 ? '' : 's'} of MV with two EU loss per tile.`,
  tier: 'mv',
  placeable: true,
  processKind: 'euCable',
  euAmps: amps,
  euVoltage: 128,
  euCapacity: amps * 24,
  euCableLossPerTile: 2,
})

export const mvMachineRegistry: Record<MvMachineId, MachineSpec> = {
  ...generatedMvMachines,
  mvExtruder: {
    id: 'mvExtruder',
    name: 'MV Extruder',
    description: 'Forces heated ingots through reusable precision molds to form efficient metal parts.',
    tier: 'mv',
    placeable: true,
    processKind: 'euProcess',
    euCapacity: 512,
    euVoltage: 128,
  },
  mvBatteryBuffer: batteryBuffer('mvBatteryBuffer', 1),
  mvBatteryBuffer2A: batteryBuffer('mvBatteryBuffer2A', 2),
  mvBatteryBuffer4A: batteryBuffer('mvBatteryBuffer4A', 4),
  mvBatteryBuffer8A: batteryBuffer('mvBatteryBuffer8A', 8),
  aluminiumCable2A: cable('aluminiumCable2A', 2),
  aluminiumCable4A: cable('aluminiumCable4A', 4),
  aluminiumCable8A: cable('aluminiumCable8A', 8),
  mvEnergyHatch2A: {
    id: 'mvEnergyHatch2A',
    name: '2A MV Energy Hatch',
    description: 'A two-amp MV power interface for shared multiblocks.',
    tier: 'mv',
    placeable: true,
    processKind: 'euHatch',
    euCapacity: 512,
    euAmps: 2,
    euVoltage: 128,
  },
  mvInputBus: { id: 'mvInputBus', name: 'MV Input Bus', description: 'A larger MV item input interface.', tier: 'mv', placeable: true, processKind: 'itemBus' },
  mvOutputBus: { id: 'mvOutputBus', name: 'MV Output Bus', description: 'A larger MV item output interface.', tier: 'mv', placeable: true, processKind: 'itemBus' },
  mvFluidInputHatch: {
    id: 'mvFluidInputHatch',
    name: 'MV Fluid Input Hatch',
    description: 'A 256L MV fluid input interface.',
    tier: 'mv',
    placeable: true,
    processKind: 'fluidHatch',
    fluidCapacityLitres: 256,
    fluidBuffers: [{ id: 'input', label: 'Input hatch', capacityLitres: 256, access: 'input', fluidRule: 'any' }],
  },
  mvFluidOutputHatch: {
    id: 'mvFluidOutputHatch',
    name: 'MV Fluid Output Hatch',
    description: 'A 256L MV fluid output interface.',
    tier: 'mv',
    placeable: true,
    processKind: 'fluidHatch',
    fluidCapacityLitres: 256,
    fluidOutputLitresPerSecond: 48,
    fluidBuffers: [{ id: 'output', label: 'Output hatch', capacityLitres: 256, access: 'output', fluidRule: 'any' }],
  },
}

const crafting = (
  id: string,
  name: string,
  inputs: Recipe['inputs'],
  outputs: Recipe['outputs'],
  pattern: Recipe['pattern'],
  machineOutputs?: Recipe['machineOutputs'],
  machineInputs?: Recipe['machineInputs'],
): Recipe => ({
  id,
  name,
  description: `Bootstrap ${name.toLowerCase()} with LV-era tools and machinery before the MV line is operational.`,
  tier: 'mv',
  stationType: 'hand',
  recipeType: 'crafting',
  durationMs: 8_000,
  inputs,
  outputs,
  pattern,
  machineOutputs,
  machineInputs,
})

export const mvCraftingRecipes: Recipe[] = [
  crafting('craft_phenolic_board', 'Phenolic Board', [{ id: 'woodPulp', amount: 2 }, { id: 'pipeSealant', amount: 1 }], [{ id: 'phenolicBoard', amount: 1 }], ['woodPulp', 'pipeSealant', 'woodPulp', null, null, null, null, null, null]),
  crafting('craft_mv_circuit', 'Good Electronic Circuit', [{ id: 'mvCircuitBoard', amount: 1 }, { id: 'primitiveCircuit', amount: 3 }, { id: 'diode', amount: 2 }, { id: 'fineGoldWire', amount: 1 }], [{ id: 'mvCircuit', amount: 1 }], ['primitiveCircuit', 'diode', 'primitiveCircuit', 'fineGoldWire', 'mvCircuitBoard', 'diode', null, 'primitiveCircuit', null]),
  crafting('craft_mv_machine_casing', 'MV Machine Casing', [{ id: 'aluminiumPlate', amount: 8 }], [{ id: 'mvMachineCasing', amount: 1 }], ['aluminiumPlate', 'aluminiumPlate', 'aluminiumPlate', 'aluminiumPlate', null, 'aluminiumPlate', 'aluminiumPlate', 'aluminiumPlate', 'aluminiumPlate']),
  crafting('craft_mv_machine_hull', 'MV Machine Hull', [{ id: 'mvMachineCasing', amount: 1 }, { id: 'aluminiumCable', amount: 2 }, { id: 'steelPlate', amount: 2 }], [{ id: 'mvMachineHull', amount: 1 }], ['steelPlate', 'aluminiumCable', 'steelPlate', null, 'mvMachineCasing', null, null, 'aluminiumCable', null]),
  crafting('craft_magnetic_steel_rod', 'Magnetic Steel Rod', [{ id: 'steelRod', amount: 1 }, { id: 'redstoneDust', amount: 4 }], [{ id: 'magneticSteelRod', amount: 1 }], ['redstoneDust', 'steelRod', 'redstoneDust', null, 'redstoneDust', null, null, 'redstoneDust', null]),
  crafting('craft_bronze_rotor', 'Bronze Rotor', [{ id: 'bronzePlate', amount: 4 }, { id: 'bronzeRing', amount: 1 }, { id: 'bronzeScrew', amount: 2 }], [{ id: 'bronzeRotor', amount: 1 }], ['bronzePlate', 'bronzeScrew', 'bronzePlate', null, 'bronzeRing', null, 'bronzePlate', 'bronzeScrew', 'bronzePlate']),
  crafting('craft_steel_pipe_section', 'Steel Pipe Section', [{ id: 'steelPlate', amount: 3 }, { id: 'steelRing', amount: 2 }], [{ id: 'steelPipeSection', amount: 1 }], ['steelRing', 'steelPlate', 'steelRing', null, 'steelPlate', null, null, 'steelPlate', null]),
  crafting('craft_mv_motor', 'MV Motor', [{ id: 'magneticSteelRod', amount: 1 }, { id: 'aluminiumWire', amount: 4 }, { id: 'aluminiumCable', amount: 2 }, { id: 'steelRod', amount: 2 }], [{ id: 'mvMotor', amount: 1 }], ['aluminiumWire', 'aluminiumCable', 'aluminiumWire', 'steelRod', 'magneticSteelRod', 'steelRod', 'aluminiumWire', 'aluminiumCable', 'aluminiumWire']),
  crafting('craft_mv_piston', 'MV Piston', [{ id: 'mvMotor', amount: 1 }, { id: 'aluminiumPlate', amount: 3 }, { id: 'aluminiumRod', amount: 2 }, { id: 'aluminiumGear', amount: 1 }], [{ id: 'mvPiston', amount: 1 }], ['aluminiumPlate', 'aluminiumRod', 'aluminiumPlate', 'aluminiumRod', 'mvMotor', 'aluminiumGear', null, 'aluminiumPlate', null]),
  crafting('craft_mv_pump', 'MV Pump', [{ id: 'mvMotor', amount: 1 }, { id: 'bronzeRotor', amount: 1 }, { id: 'steelPipeSection', amount: 1 }, { id: 'aluminiumCable', amount: 2 }, { id: 'rubber', amount: 2 }], [{ id: 'mvPump', amount: 1 }], ['rubber', 'aluminiumCable', 'rubber', 'steelPipeSection', 'mvMotor', 'bronzeRotor', null, 'aluminiumCable', null]),
  crafting('craft_mv_conveyor', 'MV Conveyor', [{ id: 'mvMotor', amount: 2 }, { id: 'aluminiumCable', amount: 2 }, { id: 'rubber', amount: 5 }], [{ id: 'mvConveyor', amount: 1 }], ['rubber', 'mvMotor', 'rubber', 'aluminiumCable', 'rubber', 'aluminiumCable', 'rubber', 'mvMotor', 'rubber']),
  crafting('craft_empty_mv_battery_hull', 'Empty MV Battery Hull', [{ id: 'batteryAlloyPlate', amount: 2 }, { id: 'aluminiumCable', amount: 1 }, { id: 'rubber', amount: 1 }], [{ id: 'emptyMvBatteryHull', amount: 1 }], ['batteryAlloyPlate', 'rubber', 'batteryAlloyPlate', null, 'aluminiumCable', null, null, null, null]),
]

const upgradePartByMachine: Partial<Record<MvMachineId, ResourceId>> = {
  mvMacerator: 'mvMotor',
  mvForgeHammer: 'mvPiston',
  mvCompressor: 'mvPiston',
  mvExtractor: 'mvPiston',
  mvAlloySmelter: 'mvCircuit',
  mvFurnace: 'mvCircuit',
  mvWiremill: 'mvMotor',
  mvBender: 'mvPiston',
  mvLathe: 'mvMotor',
  mvElectrolyzer: 'mvPump',
  mvAssembler: 'mvConveyor',
  mvMixer: 'mvMotor',
  mvCentrifuge: 'mvMotor',
  mvCanner: 'mvPump',
  mvAutoMiner: 'mvPiston',
  mvChemicalReactor: 'mvPump',
  mvAirCollector: 'mvPump',
  mvDistillery: 'mvPump',
}

const lvMachineByMv: Record<(typeof mvProcessMachines)[number][0], MachineId> = {
  mvMacerator: 'lvMacerator',
  mvForgeHammer: 'lvForgeHammer',
  mvCompressor: 'lvCompressor',
  mvExtractor: 'lvExtractor',
  mvAlloySmelter: 'lvAlloySmelter',
  mvFurnace: 'lvFurnace',
  mvWiremill: 'lvWiremill',
  mvBender: 'lvBender',
  mvLathe: 'lvLathe',
  mvElectrolyzer: 'lvElectrolyzer',
  mvAssembler: 'lvAssembler',
  mvMixer: 'lvMixer',
  mvCentrifuge: 'lvCentrifuge',
  mvCanner: 'lvCanner',
  mvAutoMiner: 'lvAutoMiner',
  mvChemicalReactor: 'lvChemicalReactor',
  mvAirCollector: 'lvAirCollector',
  mvDistillery: 'lvDistillery',
}

export const mvMachineBuildRecipes: Recipe[] = [
  ...mvProcessMachines.map(([mvId, name]) => {
    const lvId = lvMachineByMv[mvId]
    const part = upgradePartByMachine[mvId]!
    return crafting(
      `upgrade_${mvId}`,
      name,
      [{ id: 'mvMachineHull', amount: 1 }, { id: 'mvCircuit', amount: 2 }, { id: part, amount: 1 }, { id: 'aluminiumPlate', amount: 2 }],
      [],
      ['aluminiumPlate', 'mvCircuit', 'aluminiumPlate', part, 'mvMachineHull', { kind: 'machine', id: lvId }, null, 'mvCircuit', null],
      [{ id: mvId, amount: 1 }],
      [{ id: lvId, amount: 1 }],
    )
  }),
  crafting(
    'build_mv_extruder',
    'MV Extruder',
    [
      { id: 'mvMachineHull', amount: 1 },
      { id: 'mvCircuit', amount: 2 },
      { id: 'mvPiston', amount: 2 },
      { id: 'aluminiumPlate', amount: 2 },
    ],
    [],
    ['aluminiumPlate', 'mvCircuit', 'aluminiumPlate', 'mvPiston', 'mvMachineHull', 'mvPiston', null, 'mvCircuit', null],
    [{ id: 'mvExtruder', amount: 1 }],
  ),
]

const cableRecipes: Recipe[] = ([2, 4, 8] as const).map((amps) => {
  const sourceCableId = amps === 2 ? 'aluminiumCable' : `aluminiumCable${amps / 2}A` as ResourceId
  const outputCableId = `aluminiumCable${amps}A` as ResourceId
  return crafting(
    `craft_aluminium_cable_${amps}a`,
    `${amps}A Aluminium Cable`,
    [{ id: sourceCableId, amount: 2 }, { id: 'rubber', amount: 1 }],
    [{ id: outputCableId, amount: 1 }],
    [sourceCableId, 'rubber', sourceCableId, null, null, null, null, null, null],
  )
})

const bufferRecipes: Recipe[] = ([1, 2, 4, 8] as const).map((amps) => {
  const id = amps === 1 ? 'mvBatteryBuffer' : `mvBatteryBuffer${amps}A` as MvMachineId
  const cableId = amps === 1 ? 'aluminiumCable' : `aluminiumCable${amps}A` as ResourceId
  return crafting(
    `craft_${id}`,
    `${amps}A MV Battery Buffer`,
    [{ id: 'mvMachineHull', amount: 1 }, { id: cableId, amount: 1 }, { id: 'mvCircuit', amount: 1 }],
    [],
    [cableId, null, null, null, 'mvMachineHull', null, null, 'mvCircuit', null],
    [{ id, amount: 1 }],
  )
})

export const mvInfrastructureRecipes: Recipe[] = [
  ...cableRecipes,
  ...bufferRecipes,
  ...([
    ['mvEnergyHatch2A', '2A MV Energy Hatch', 'aluminiumCable2A', ['aluminiumPlate', 'aluminiumCable2A', 'aluminiumPlate', null, 'mvMachineHull', null, null, 'mvCircuit', null]],
    ['mvInputBus', 'MV Input Bus', 'mvConveyor', ['aluminiumPlate', 'mvConveyor', 'aluminiumPlate', null, 'mvMachineHull', null, null, 'mvCircuit', null]],
    ['mvOutputBus', 'MV Output Bus', 'mvConveyor', ['aluminiumPlate', 'mvCircuit', 'aluminiumPlate', null, 'mvMachineHull', null, null, 'mvConveyor', null]],
    ['mvFluidInputHatch', 'MV Fluid Input Hatch', 'mvPump', ['aluminiumPlate', 'mvPump', 'aluminiumPlate', null, 'mvMachineHull', null, null, 'mvCircuit', null]],
    ['mvFluidOutputHatch', 'MV Fluid Output Hatch', 'mvPump', ['aluminiumPlate', 'mvCircuit', 'aluminiumPlate', null, 'mvMachineHull', null, null, 'mvPump', null]],
  ] as const).map(([id, name, part, pattern]) => crafting(
    `craft_${id}`,
    name,
    [{ id: 'mvMachineHull', amount: 1 }, { id: part, amount: 1 }, { id: 'mvCircuit', amount: 1 }, { id: 'aluminiumPlate', amount: 2 }],
    [],
    [...pattern],
    [{ id, amount: 1 }],
  )),
]

const extrusionMoldRecipes: ProcessRecipe[] = ([
  ['plate', 'extrusionMoldPlate', 'steelPlate', 5],
  ['rod', 'extrusionMoldRod', 'steelRod', 6],
  ['bolt', 'extrusionMoldBolt', 'steelBolt', 7],
  ['ring', 'extrusionMoldRing', 'steelRing', 8],
  ['gear', 'extrusionMoldGear', 'steelGear', 9],
] as const).map(([form, moldId, referenceId, programNumber]) => ({
  id: `imprint_extrusion_mold_${form}`,
  name: `Cut ${form[0].toUpperCase()}${form.slice(1)} Extrusion Mold`,
  description: 'Cut a reusable extrusion profile into a hardened blank using a finished steel part as the reference.',
  tier: 'mv',
  machineId: 'circuitImprinter',
  durationMs: 12_000,
  euCost: 256,
  input: { id: 'hardenedDieBlank', amount: 1 },
  secondaryInput: { id: referenceId, amount: 1 },
  output: { id: moldId, amount: 1 },
  programNumber,
  autoSelectable: false,
}))

const extrusionFormRecipes: ProcessRecipe[] = materialFamilies.flatMap((family) => ([
  ['plate', 'extrusionMoldPlate', 1, 1],
  ['rod', 'extrusionMoldRod', 1, 2],
  ['bolt', 'extrusionMoldBolt', 1, 8],
  ['ring', 'extrusionMoldRing', 1, 4],
  ['gear', 'extrusionMoldGear', 4, 1],
] as const).map(([form, moldId, ingotAmount, outputAmount]): ProcessRecipe => ({
  id: `mv_extrude_${family.id}_${form}`,
  name: `Extrude ${family.label} ${form[0].toUpperCase()}${form.slice(1)}`,
  description: 'Force ingots through a retained precision mold for a high-yield MV forming route.',
  tier: 'mv',
  machineId: 'mvExtruder',
  durationMs: form === 'gear' ? 12_000 : 8_000,
  euCost: 512,
  input: { id: family.forms.ingot, amount: ingotAmount },
  secondaryInput: { id: moldId, amount: 1 },
  output: { id: family.forms[form], amount: outputAmount },
})))

export const mvExclusiveProcessRecipes: ProcessRecipe[] = [
  ...extrusionMoldRecipes,
  ...extrusionFormRecipes,
  {
    id: 'lv_macerate_sphalerite',
    name: 'Prepare Sphalerite Concentrate',
    description: 'Crush sphalerite into a gallium-bearing concentrate while recovering zinc and sulfur.',
    tier: 'lv',
    machineId: 'lvMacerator',
    durationMs: 24_000,
    euCost: 384,
    input: { id: 'sphaleriteOre', amount: 4 },
    output: { id: 'sphaleriteConcentrate', amount: 2 },
    secondaryOutput: { id: 'zincDust', amount: 1 },
  },
  {
    id: 'lv_centrifuge_sphalerite',
    name: 'Recover Gallium',
    description: 'Separate trace gallium from prepared sphalerite concentrate.',
    tier: 'lv',
    machineId: 'lvCentrifuge',
    durationMs: 45_000,
    euCost: 720,
    input: { id: 'sphaleriteConcentrate', amount: 4 },
    output: { id: 'galliumDust', amount: 1 },
    secondaryOutput: { id: 'sulfurDust', amount: 1 },
  },
  {
    id: 'lv_macerate_realgar',
    name: 'Process Realgar',
    description: 'Crush realgar into arsenic feed with sulfur as a useful byproduct.',
    tier: 'lv',
    machineId: 'lvMacerator',
    durationMs: 24_000,
    euCost: 384,
    input: { id: 'realgarOre', amount: 4 },
    output: { id: 'arsenicDust', amount: 2 },
    secondaryOutput: { id: 'sulfurDust', amount: 1 },
  },
  {
    id: 'lv_mix_gallium_arsenide',
    name: 'Mix Gallium Arsenide',
    description: 'Blend equal Gallium and Arsenic powders before crystal growth.',
    tier: 'lv',
    machineId: 'lvMixer',
    durationMs: 24_000,
    euCost: 384,
    input: { id: 'galliumDust', amount: 1 },
    secondaryInput: { id: 'arsenicDust', amount: 1 },
    output: { id: 'galliumArsenideDust', amount: 1 },
  },
  {
    id: 'arc_gallium_arsenide',
    name: 'Grow Gallium Arsenide Crystal',
    description: 'Grow a prepared gallium arsenide charge under oxygen-assisted arc conditions.',
    tier: 'mv',
    machineId: 'arcBlastFurnace',
    durationMs: 48_000,
    euCost: 2_160,
    requiredEuAmps: 4,
    input: { id: 'galliumArsenideDust', amount: 1 },
    fluidInput: { id: 'oxygen', amount: 4 },
    output: { id: 'galliumArsenideCrystal', amount: 1 },
  },
  {
    id: 'lv_macerate_gallium_arsenide',
    name: 'Powder Gallium Arsenide',
    description: 'Prepare semiconductor-grade gallium arsenide powder.',
    tier: 'lv',
    machineId: 'lvMacerator',
    durationMs: 16_000,
    euCost: 256,
    input: { id: 'galliumArsenideCrystal', amount: 1 },
    output: { id: 'galliumArsenideDust', amount: 1 },
  },
  {
    id: 'lv_assembler_phenolic_board',
    name: 'Press Phenolic Board',
    description: 'Press Wood Pulp with Glue for an automated phenolic board route.',
    tier: 'lv',
    machineId: 'lvAssembler',
    durationMs: 16_000,
    euCost: 256,
    input: { id: 'woodPulp', amount: 2 },
    fluidInput: { id: 'glue', amount: 2 },
    output: { id: 'phenolicBoard', amount: 1 },
  },
  {
    id: 'lv_assembler_mv_circuit_board',
    name: 'Etch MV Circuit Board',
    description: 'Etch fine gold traces into a phenolic board with sulfuric acid.',
    tier: 'lv',
    machineId: 'lvAssembler',
    durationMs: 24_000,
    euCost: 384,
    input: { id: 'phenolicBoard', amount: 1 },
    secondaryInput: { id: 'fineGoldWire', amount: 4 },
    fluidInput: { id: 'sulfuricAcid', amount: 8 },
    output: { id: 'mvCircuitBoard', amount: 1 },
    programNumber: 6,
    autoSelectable: false,
  },
  {
    id: 'lv_compress_mv_machine_casing',
    name: 'Press MV Machine Casing',
    description: 'Press eight Aluminium Plates into a square MV machine shell.',
    tier: 'mv',
    machineId: 'lvCompressor',
    durationMs: 24_000,
    euCost: 384,
    input: { id: 'aluminiumPlate', amount: 8 },
    output: { id: 'mvMachineCasing', amount: 1 },
  },
  {
    id: 'lv_assemble_mv_machine_hull',
    name: 'Assemble MV Machine Hull',
    description: 'Line an MV casing with Steel Plate and Aluminium Cable.',
    tier: 'mv',
    machineId: 'lvAssembler',
    durationMs: 20_000,
    euCost: 320,
    input: { id: 'mvMachineCasing', amount: 1 },
    secondaryInput: { id: 'steelPlate', amount: 2 },
    extraInputs: [{ id: 'aluminiumCable', amount: 2 }],
    output: { id: 'mvMachineHull', amount: 1 },
  },
  {
    id: 'lv_assemble_mv_motor',
    name: 'Assemble MV Motor',
    description: 'Wind an MV motor around a magnetised steel shaft.',
    tier: 'mv',
    machineId: 'lvAssembler',
    durationMs: 20_000,
    euCost: 320,
    input: { id: 'magneticSteelRod', amount: 1 },
    secondaryInput: { id: 'aluminiumWire', amount: 4 },
    extraInputs: [{ id: 'aluminiumCable', amount: 2 }, { id: 'steelRod', amount: 2 }],
    output: { id: 'mvMotor', amount: 1 },
  },
  {
    id: 'lv_assemble_mv_piston',
    name: 'Assemble MV Piston',
    description: 'Build the MV actuator with aluminium motion parts.',
    tier: 'mv',
    machineId: 'lvAssembler',
    durationMs: 20_000,
    euCost: 320,
    input: { id: 'mvMotor', amount: 1 },
    secondaryInput: { id: 'aluminiumPlate', amount: 3 },
    extraInputs: [{ id: 'aluminiumRod', amount: 2 }, { id: 'aluminiumGear', amount: 1 }],
    output: { id: 'mvPiston', amount: 1 },
  },
  {
    id: 'lv_assemble_mv_pump',
    name: 'Assemble MV Pump',
    description: 'Seal an MV pump around a bronze rotor and steel pipe.',
    tier: 'mv',
    machineId: 'lvAssembler',
    durationMs: 20_000,
    euCost: 320,
    input: { id: 'mvMotor', amount: 1 },
    secondaryInput: { id: 'bronzeRotor', amount: 1 },
    extraInputs: [
      { id: 'steelPipeSection', amount: 1 },
      { id: 'aluminiumCable', amount: 2 },
      { id: 'rubber', amount: 2 },
    ],
    output: { id: 'mvPump', amount: 1 },
  },
  {
    id: 'lv_assemble_mv_conveyor',
    name: 'Assemble MV Conveyor',
    description: 'Pair two MV motors inside a reinforced rubber belt.',
    tier: 'mv',
    machineId: 'lvAssembler',
    durationMs: 20_000,
    euCost: 320,
    input: { id: 'mvMotor', amount: 2 },
    secondaryInput: { id: 'aluminiumCable', amount: 2 },
    extraInputs: [{ id: 'rubber', amount: 5 }],
    output: { id: 'mvConveyor', amount: 1 },
  },
  {
    id: 'lv_assembler_diodes',
    name: 'Assemble Diodes',
    description: 'Package gallium arsenide junctions with fine copper leads and glass.',
    tier: 'lv',
    machineId: 'lvAssembler',
    durationMs: 18_000,
    euCost: 288,
    input: { id: 'galliumArsenideDust', amount: 1 },
    secondaryInput: { id: 'fineCopperWire', amount: 2 },
    extraInputs: [{ id: 'glass', amount: 1 }],
    output: { id: 'diode', amount: 4 },
    programNumber: 7,
    autoSelectable: false,
  },
  {
    id: 'lv_canner_mv_lithium_battery',
    name: 'Fill MV Lithium Battery',
    description: 'Seal a larger lithium charge into an MV battery hull.',
    tier: 'mv',
    machineId: 'lvCanner',
    durationMs: 30_000,
    euCost: 480,
    input: { id: 'emptyMvBatteryHull', amount: 1 },
    secondaryInput: { id: 'lithiumDust', amount: 8 },
    output: { id: 'mvLithiumBattery', amount: 1 },
  },
]

const mvByLv = Object.fromEntries(Object.entries(lvMachineByMv).map(([mv, lv]) => [lv, mv])) as Partial<Record<MachineId, MvMachineId>>

export const generateMvInheritedProcessRecipes = (authored: ProcessRecipe[]): ProcessRecipe[] => authored.flatMap((recipe) => {
  const mvMachineId = mvByLv[recipe.machineId]
  if (!mvMachineId || mvMachineId === 'mvAutoMiner') return []
  return [{
    ...recipe,
    id: `mv_inherited_${recipe.id}`,
    name: recipe.name.replace(/^LV /, 'MV '),
    description: `${recipe.description} The MV machine completes this established recipe in half the time.`,
    tier: 'mv',
    machineId: mvMachineId,
    durationMs: Math.max(1_000, Math.ceil(recipe.durationMs / 2)),
    euCost: Math.max(1, Math.ceil((recipe.euCost ?? 0) * 2)),
  }]
})
