export const mvResourceIds = [
  'sphaleriteOre',
  'realgarOre',
  'sphaleriteConcentrate',
  'zincDust',
  'arsenicDust',
  'galliumDust',
  'galliumArsenideCrystal',
  'galliumArsenideDust',
  'phenolicBoard',
  'mvCircuitBoard',
  'diode',
  'mvCircuit',
  'mvMachineCasing',
  'mvMachineHull',
  'magneticSteelRod',
  'bronzeRotor',
  'steelPipeSection',
  'mvMotor',
  'mvPiston',
  'mvPump',
  'mvConveyor',
  'emptyMvBatteryHull',
  'mvLithiumBattery',
  'aluminiumCable2A',
  'aluminiumCable4A',
  'aluminiumCable8A',
  'extrusionMoldPlate',
  'extrusionMoldRod',
  'extrusionMoldBolt',
  'extrusionMoldRing',
  'extrusionMoldGear',
] as const

export type MvResourceId = (typeof mvResourceIds)[number]

export const mvMachineIds = [
  'mvMacerator',
  'mvForgeHammer',
  'mvCompressor',
  'mvExtractor',
  'mvAlloySmelter',
  'mvFurnace',
  'mvWiremill',
  'mvBender',
  'mvLathe',
  'mvElectrolyzer',
  'mvAssembler',
  'mvMixer',
  'mvCentrifuge',
  'mvCanner',
  'mvAutoMiner',
  'mvChemicalReactor',
  'mvAirCollector',
  'mvDistillery',
  'mvExtruder',
  'mvBatteryBuffer',
  'mvBatteryBuffer2A',
  'mvBatteryBuffer4A',
  'mvBatteryBuffer8A',
  'aluminiumCable2A',
  'aluminiumCable4A',
  'aluminiumCable8A',
  'mvEnergyHatch2A',
  'mvInputBus',
  'mvOutputBus',
  'mvFluidInputHatch',
  'mvFluidOutputHatch',
] as const

export type MvMachineId = (typeof mvMachineIds)[number]
