import type { MachineSpec, ProcessRecipe, Quest, Recipe, ResourceSpec } from './types'

export const polymerResourceRegistry = {
  bagasse: { id: 'bagasse', label: 'Bagasse', category: 'raw', tier: 'lv' },
  plateMold: { id: 'plateMold', label: 'Plate Mold', category: 'tool', tier: 'lv' },
  polyethylenePlate: { id: 'polyethylenePlate', label: 'Polyethylene Plate', category: 'plate', tier: 'lv' },
  polyethylenePipe: { id: 'polyethylenePipe', label: 'Polyethylene Pipe', category: 'component', tier: 'lv' },
  tankCasing1: { id: 'tankCasing1', label: 'Tank Casing I', category: 'machinePart', tier: 'mv' },
  pulsatingIronIngot: { id: 'pulsatingIronIngot', label: 'Pulsating Iron Ingot', category: 'ingot', tier: 'mv' },
  pulsatingIronPlate: { id: 'pulsatingIronPlate', label: 'Pulsating Iron Plate', category: 'plate', tier: 'mv' },
} satisfies Record<string, ResourceSpec>

export const polymerMachineRegistry = {
  lvFluidSolidifier: {
    id: 'lvFluidSolidifier',
    name: 'LV Fluid Solidifier',
    description: 'Casts measured liquid materials through a reusable mold.',
    tier: 'lv',
    placeable: true,
    processKind: 'euProcess',
    euCapacity: 128,
    euVoltage: 32,
    fluidCapacityLitres: 32,
    fluidBuffers: [
      { id: 'feed', label: 'Fluid input', capacityLitres: 32, access: 'input', fluidRule: 'recipe-inputs' },
    ],
  },
  lvSuperTank: {
    id: 'lvSuperTank',
    name: 'LV Super Tank I',
    description: 'A hermetically lined single-fluid tank holding 4,000,000L.',
    tier: 'mv',
    placeable: true,
    processKind: 'steamStorage',
    steamCapacityLitres: 4_000_000,
    fluidCapacityLitres: 4_000_000,
    fluidOutputLitresPerSecond: 192,
    fluidBuffers: [
      { id: 'storage', label: 'Tank storage', capacityLitres: 4_000_000, access: 'both', fluidRule: 'any' },
    ],
  },
} satisfies Record<string, MachineSpec>

export const polymerCraftingRecipes: Recipe[] = [
  {
    id: 'craft_plate_mold',
    name: 'Shape Plate Mold',
    description: 'File and hammer four steel plates into a reusable casting mold.',
    tier: 'lv',
    durationMs: 8_000,
    inputs: [{ id: 'steelPlate', amount: 4 }],
    catalysts: [{ id: 'ironFile', amount: 1 }, { id: 'ironHammer', amount: 1 }],
    durabilityCosts: [{ id: 'ironFile', amount: 1 }, { id: 'ironHammer', amount: 1 }],
    pattern: ['ironFile', 'steelPlate', null, 'steelPlate', 'steelPlate', 'steelPlate', null, 'ironHammer', null],
    outputs: [{ id: 'plateMold', amount: 1 }],
  },
  {
    id: 'craft_lv_fluid_solidifier',
    name: 'Build LV Fluid Solidifier',
    description: 'Twin pumps feed a controlled casting chamber around a standard storage chest.',
    tier: 'lv',
    durationMs: 10_000,
    inputs: [
      { id: 'lvPump', amount: 2 },
      { id: 'glass', amount: 1 },
      { id: 'tinCable', amount: 2 },
      { id: 'lvMachineHull', amount: 1 },
      { id: 'primitiveCircuit', amount: 2 },
    ],
    machineInputs: [{ id: 'standardChest', amount: 1 }],
    pattern: ['lvPump', 'glass', 'lvPump', 'tinCable', 'lvMachineHull', 'tinCable', 'primitiveCircuit', { kind: 'machine', id: 'standardChest' }, 'primitiveCircuit'],
    outputs: [],
    machineOutputs: [{ id: 'lvFluidSolidifier', amount: 1 }],
  },
  {
    id: 'craft_polyethylene_pipe',
    name: 'Form Polyethylene Pipe',
    description: 'Join six polyethylene plates into a thick chemical-resistant pipe.',
    tier: 'lv',
    durationMs: 6_000,
    inputs: [{ id: 'polyethylenePlate', amount: 6 }],
    pattern: ['polyethylenePlate', 'polyethylenePlate', 'polyethylenePlate', null, null, null, 'polyethylenePlate', 'polyethylenePlate', 'polyethylenePlate'],
    outputs: [{ id: 'polyethylenePipe', amount: 1 }],
  },
  {
    id: 'craft_tank_casing_1',
    name: 'Build Tank Casing I',
    description: 'Seal a polyethylene pipe inside eight steel pressure plates.',
    tier: 'mv',
    durationMs: 9_000,
    inputs: [{ id: 'steelPlate', amount: 8 }, { id: 'polyethylenePipe', amount: 1 }],
    pattern: ['steelPlate', 'steelPlate', 'steelPlate', 'steelPlate', 'polyethylenePipe', 'steelPlate', 'steelPlate', 'steelPlate', 'steelPlate'],
    outputs: [{ id: 'tankCasing1', amount: 1 }],
  },
  {
    id: 'craft_lv_super_tank',
    name: 'Build LV Super Tank I',
    description: 'Combine MV pumping with LV control and a hermetically lined pressure casing.',
    tier: 'mv',
    durationMs: 12_000,
    inputs: [
      { id: 'primitiveCircuit', amount: 4 },
      { id: 'pulsatingIronPlate', amount: 1 },
      { id: 'aluminiumPlate', amount: 2 },
      { id: 'tankCasing1', amount: 1 },
      { id: 'mvPump', amount: 1 },
    ],
    pattern: ['primitiveCircuit', 'pulsatingIronPlate', 'primitiveCircuit', 'aluminiumPlate', 'tankCasing1', 'aluminiumPlate', 'primitiveCircuit', 'mvPump', 'primitiveCircuit'],
    outputs: [],
    machineOutputs: [{ id: 'lvSuperTank', amount: 1 }],
  },
]

export const polymerProcessRecipes: ProcessRecipe[] = [
  { id: 'extract_cane_juice', name: 'Extract Cane Juice', description: 'Press sugar cane without sending liquid through a macerator.', tier: 'lv', machineId: 'lvExtractor', durationMs: 60_000, euCost: 960, input: { id: 'sugarCane', amount: 24 }, output: { id: 'bagasse', amount: 12 }, fluidOutput: { id: 'caneJuice', amount: 48, bufferId: 'product' } },
  { id: 'mix_sugar_wash', name: 'Mix Sugar Wash', description: 'Dilute cane juice to a controlled fermentation strength.', tier: 'lv', machineId: 'lvMixer', durationMs: 60_000, euCost: 720, fluidOnly: true, fluidInputs: [{ id: 'caneJuice', amount: 48, bufferId: 'feed-a' }, { id: 'water', amount: 24, bufferId: 'feed-b' }], fluidOutput: { id: 'sugarWash', amount: 60, bufferId: 'product' }, programNumber: 1, autoSelectable: false },
  { id: 'ferment_sugar_wash', name: 'Ferment Sugar Wash', description: 'Convert sugar wash while capturing the carbon dioxide byproduct.', tier: 'lv', machineId: 'lvChemicalReactor', durationMs: 180_000, euCost: 1_440, fluidOnly: true, fluidInput: { id: 'sugarWash', amount: 60, bufferId: 'feedA' }, fluidOutputs: [{ id: 'fermentedWash', amount: 48, bufferId: 'reactionA' }, { id: 'carbonDioxide', amount: 12, bufferId: 'reactionB' }], programNumber: 3, autoSelectable: false },
  { id: 'distil_ethanol', name: 'Distil Ethanol', description: 'Separate ethanol and vinasse from fermented wash.', tier: 'lv', machineId: 'lvDistillery', durationMs: 90_000, euCost: 1_440, fluidOnly: true, fluidInput: { id: 'fermentedWash', amount: 48, bufferId: 'feed' }, fluidOutputs: [{ id: 'ethanol', amount: 24, bufferId: 'light' }, { id: 'vinasse', amount: 24, bufferId: 'heavy' }], programNumber: 2, autoSelectable: false },
  { id: 'dehydrate_ethanol', name: 'Dehydrate Ethanol', description: 'Use concentrated sulfuric acid to remove water and form ethylene.', tier: 'lv', machineId: 'lvChemicalReactor', durationMs: 120_000, euCost: 2_880, fluidOnly: true, fluidInputs: [{ id: 'ethanol', amount: 24, bufferId: 'feedA' }, { id: 'sulfuricAcid', amount: 4, bufferId: 'feedB' }], fluidOutputs: [{ id: 'ethylene', amount: 18, bufferId: 'reactionA' }, { id: 'dilutedSulfuricAcid', amount: 8, bufferId: 'reactionB' }], programNumber: 5, autoSelectable: false },
  { id: 'recover_sulfuric_acid', name: 'Recover Sulfuric Acid', description: 'Distil spent acid into a reusable concentrate and recovered water.', tier: 'lv', machineId: 'lvDistillery', durationMs: 60_000, euCost: 960, fluidOnly: true, fluidInput: { id: 'dilutedSulfuricAcid', amount: 8, bufferId: 'feed' }, fluidOutputs: [{ id: 'sulfuricAcid', amount: 3, bufferId: 'light' }, { id: 'water', amount: 5, bufferId: 'heavy' }], programNumber: 3, autoSelectable: false },
  { id: 'polymerize_with_air', name: 'Polymerize with Air', description: 'Polymerize ethylene using collected air at the basic yield.', tier: 'lv', machineId: 'lvChemicalReactor', durationMs: 120_000, euCost: 3_840, fluidOnly: true, fluidInputs: [{ id: 'ethylene', amount: 18, bufferId: 'feedA' }, { id: 'air', amount: 8, bufferId: 'feedB' }], fluidOutput: { id: 'liquidPolyethylene', amount: 18, bufferId: 'reactionA' }, programNumber: 6, autoSelectable: false },
  { id: 'polymerize_with_oxygen', name: 'Polymerize with Oxygen', description: 'Use separated oxygen to improve polyethylene yield by fifty percent.', tier: 'lv', machineId: 'lvChemicalReactor', durationMs: 120_000, euCost: 3_840, fluidOnly: true, fluidInputs: [{ id: 'ethylene', amount: 18, bufferId: 'feedA' }, { id: 'oxygen', amount: 2, bufferId: 'feedB' }], fluidOutput: { id: 'liquidPolyethylene', amount: 27, bufferId: 'reactionA' }, programNumber: 7, autoSelectable: false },
  { id: 'solidify_polyethylene_plate', name: 'Cast Polyethylene Plate', description: 'Cast four litres of liquid polyethylene through a reusable plate mold.', tier: 'lv', machineId: 'lvFluidSolidifier', durationMs: 8_000, euCost: 128, input: { id: 'plateMold', amount: 1 }, fluidInput: { id: 'liquidPolyethylene', amount: 4, bufferId: 'feed' }, output: { id: 'polyethylenePlate', amount: 1 }, programNumber: 1, autoSelectable: false },
  { id: 'mix_fertilizer_liquor', name: 'Mix Fertilizer Liquor', description: 'Bind vinasse and captured carbon dioxide into a reusable farm feed.', tier: 'lv', machineId: 'lvMixer', durationMs: 60_000, euCost: 720, fluidOnly: true, fluidInputs: [{ id: 'vinasse', amount: 24, bufferId: 'feed-a' }, { id: 'carbonDioxide', amount: 12, bufferId: 'feed-b' }], fluidOutput: { id: 'fertilizerLiquor', amount: 24, bufferId: 'product' }, programNumber: 4, autoSelectable: false },
  { id: 'farm_enriched_sugar_cane', name: 'Grow Enriched Sugar Cane', description: 'Recycle fertilizer liquor into a larger automated cane harvest.', tier: 'lv', machineId: 'poweredFarm', durationMs: 60_000, euCost: 800, fluidOnly: true, fluidInputs: [{ id: 'water', amount: 400, bufferId: 'water' }, { id: 'fertilizerLiquor', amount: 24, bufferId: 'fertilizer' }], output: { id: 'sugarCane', amount: 36 }, programNumber: 4, autoSelectable: false },
  { id: 'pyrolyse_bagasse', name: 'Pyrolyse Bagasse', description: 'Carbonize the dry cane fibre and capture its useful tar and gas.', tier: 'lv', machineId: 'pyrolysisOven', durationMs: 60_000, euCost: 960, input: { id: 'bagasse', amount: 12 }, output: { id: 'charcoal', amount: 4 }, fluidOutputs: [{ id: 'woodTar', amount: 12, bufferId: 'tar' }, { id: 'woodGas', amount: 4, bufferId: 'gas' }], programNumber: 3, autoSelectable: false },
  { id: 'alloy_pulsating_iron', name: 'Alloy Pulsating Iron', description: 'Bind iron around one phase crystal to make a responsive tank-control alloy.', tier: 'mv', machineId: 'lvAlloySmelter', durationMs: 30_000, euCost: 480, input: { id: 'ironIngot', amount: 1 }, secondaryInput: { id: 'phaseCrystal', amount: 1 }, output: { id: 'pulsatingIronIngot', amount: 1 }, programNumber: 8, autoSelectable: false },
  { id: 'bend_pulsating_iron', name: 'Bend Pulsating Iron Plate', description: 'Bend one pulsating iron ingot into the control plate used by Super Tank I.', tier: 'mv', machineId: 'lvBender', durationMs: 4_000, euCost: 64, input: { id: 'pulsatingIronIngot', amount: 1 }, output: { id: 'pulsatingIronPlate', amount: 1 } },
]

export const polymerQuests: Quest[] = [
  { id: 'growSugarCaneQuest', chapterId: 'polymerWorks', chapter: 'Polymer Works', title: 'A sweeter feedstock', description: 'Select the Sugar Cane program on a Powered Farm and keep its water route supplied.', position: { x: 80, y: 120 }, icon: { type: 'resource', id: 'sugarCane' }, prerequisites: ['formPoweredFarmQuest', 'separateAirQuest', 'makeSulfuricAcidQuest'], requirements: { recipes: [{ id: 'farm_sugar_cane', amount: 1 }] }, rewards: { scrip: 12 } },
  { id: 'extractCaneJuiceQuest', chapterId: 'polymerWorks', chapter: 'Polymer Works', title: 'Do not put this in a Macerator', description: 'Press cane in the LV Extractor. Bagasse leaves as an item while Cane Juice uses the fluid output.', position: { x: 270, y: 120 }, icon: { type: 'resource', id: 'bagasse' }, prerequisites: ['growSugarCaneQuest'], requirements: { recipes: [{ id: 'extract_cane_juice', amount: 1 }] }, rewards: { scrip: 12 } },
  { id: 'mixSugarWashQuest', chapterId: 'polymerWorks', chapter: 'Polymer Works', title: 'Wash before fermenting', description: 'Dilute Cane Juice with Water in the LV Mixer.', position: { x: 460, y: 120 }, icon: { type: 'machine', id: 'lvMixer' }, prerequisites: ['extractCaneJuiceQuest'], requirements: { recipes: [{ id: 'mix_sugar_wash', amount: 1 }] }, rewards: { scrip: 12 } },
  { id: 'fermentSugarWashQuest', chapterId: 'polymerWorks', chapter: 'Polymer Works', title: 'Industrial home brewing', description: 'Ferment Sugar Wash in a Chemical Reactor. Route both outputs or captured CO2 will stop the next batch.', position: { x: 650, y: 120 }, icon: { type: 'machine', id: 'lvChemicalReactor' }, prerequisites: ['mixSugarWashQuest'], requirements: { recipes: [{ id: 'ferment_sugar_wash', amount: 1 }] }, rewards: { scrip: 12 } },
  { id: 'distilEthanolQuest', chapterId: 'polymerWorks', chapter: 'Polymer Works', title: 'The Distillery is not a pub', description: 'Distil the fermented wash and make room for both Ethanol and Vinasse.', position: { x: 840, y: 120 }, icon: { type: 'machine', id: 'lvDistillery' }, prerequisites: ['fermentSugarWashQuest'], requirements: { recipes: [{ id: 'distil_ethanol', amount: 1 }] }, rewards: { scrip: 12 } },
  { id: 'dehydrateEthanolQuest', chapterId: 'polymerWorks', chapter: 'Polymer Works', title: 'Borrowed acid', description: 'Use Sulfuric Acid to turn Ethanol into Ethylene. The acid leaves diluted, not destroyed.', position: { x: 1030, y: 120 }, icon: { type: 'resource', id: 'sulfurDust' }, prerequisites: ['distilEthanolQuest'], requirements: { recipes: [{ id: 'dehydrate_ethanol', amount: 1 }] }, rewards: { scrip: 16 } },
  { id: 'recoverAcidQuest', chapterId: 'polymerWorks', chapter: 'Polymer Works', title: 'Give most of it back', description: 'Recover concentrated acid and water in the Distillery. Each cycle still needs a small sulfur top-up.', kind: 'optional', position: { x: 1030, y: 320 }, icon: { type: 'machine', id: 'lvDistillery' }, prerequisites: ['dehydrateEthanolQuest'], requirements: { recipes: [{ id: 'recover_sulfuric_acid', amount: 1 }] }, rewards: { scrip: 8 } },
  { id: 'oxygenPolymerTipQuest', chapterId: 'polymerWorks', chapter: 'Polymer Works', title: 'Air works, Oxygen works better', description: 'Program 6 accepts Air. Program 7 uses separated Oxygen for fifty percent more liquid plastic from the same Ethylene.', kind: 'optional', position: { x: 1220, y: 320 }, icon: { type: 'machine', id: 'lvCentrifuge' }, prerequisites: ['dehydrateEthanolQuest'], requirements: { recipes: [{ id: 'polymerize_with_oxygen', amount: 1 }] }, rewards: { scrip: 8 } },
  {
    id: 'makeLiquidPolyethyleneQuest',
    chapterId: 'polymerWorks',
    chapter: 'Polymer Works',
    title: 'Plastic, still technically liquid',
    description: 'Polymerize Ethylene with Air on program 6, or use Oxygen on program 7 for the improved yield. Either route completes this step.',
    position: { x: 1220, y: 120 },
    icon: { type: 'machine', id: 'lvChemicalReactor' },
    prerequisites: ['dehydrateEthanolQuest'],
    objectives: [{
      type: 'recipeAny',
      ids: ['polymerize_with_air', 'polymerize_with_oxygen'],
      amount: 1,
      label: 'Produce Liquid Polyethylene',
    }],
    requirements: {},
    rewards: { scrip: 16 },
  },
  { id: 'castPolyethyleneQuest', chapterId: 'polymerWorks', chapter: 'Polymer Works', title: 'Shape matters', description: 'Build the LV Fluid Solidifier, insert the reusable Plate Mold, and cast six Polyethylene Plates.', position: { x: 1410, y: 120 }, icon: { type: 'machine', id: 'lvFluidSolidifier' }, prerequisites: ['makeLiquidPolyethyleneQuest'], requirements: { machines: [{ id: 'lvFluidSolidifier', amount: 1 }], recipes: [{ id: 'solidify_polyethylene_plate', amount: 6 }] }, rewards: { scrip: 16 } },
  { id: 'craftPolyethylenePipeQuest', chapterId: 'polymerWorks', chapter: 'Polymer Works', title: 'A questionable plastic pipe', description: 'Arrange six Polyethylene Plates around an empty centre row to craft the pressure liner.', position: { x: 1600, y: 120 }, icon: { type: 'resource', id: 'polyethylenePipe' }, prerequisites: ['castPolyethyleneQuest'], requirements: { resources: [{ id: 'polyethylenePipe', amount: 1 }] }, rewards: { scrip: 12 } },
  { id: 'craftTankCasingQuest', chapterId: 'polymerWorks', chapter: 'Polymer Works', title: 'Hermetically sealed', description: 'Surround the Polyethylene Pipe with eight Steel Plates in the crafting grid.', position: { x: 1790, y: 120 }, icon: { type: 'resource', id: 'tankCasing1' }, prerequisites: ['craftPolyethylenePipeQuest'], requirements: { resources: [{ id: 'tankCasing1', amount: 1 }] }, rewards: { scrip: 12 } },
  { id: 'makePulsatingIronQuest', chapterId: 'polymerWorks', chapter: 'Polymer Works', title: 'Iron with a pulse', description: 'Late capstone: return after opening Auto Crafting. Alloy Iron with a Phase Crystal, then bend the ingot into the tank control plate.', kind: 'optional', position: { x: 1980, y: 120 }, icon: { type: 'resource', id: 'pulsatingIronPlate' }, prerequisites: ['craftTankCasingQuest', 'makePhaseCrystalQuest'], requirements: { resources: [{ id: 'pulsatingIronPlate', amount: 1 }] }, rewards: { scrip: 12 } },
  { id: 'buildSuperTankQuest', chapterId: 'polymerWorks', chapter: 'Polymer Works', title: 'Four million litres', description: 'Late capstone: return after making MV motion parts. Combine four LV circuits, two Aluminium Plates, one MV Pump, the Pulsating Iron Plate, and Tank Casing I, then place the finished tank.', kind: 'optional', position: { x: 2170, y: 120 }, icon: { type: 'machine', id: 'lvSuperTank' }, prerequisites: ['makePulsatingIronQuest', 'makeMvMotorQuest'], requirements: {}, objectives: [{ type: 'recipe', id: 'craft_lv_super_tank', amount: 1 }, { type: 'placedMachine', id: 'lvSuperTank', amount: 1 }], rewards: { scrip: 30 } },
  { id: 'reusePolymerByproductsQuest', chapterId: 'polymerWorks', chapter: 'Polymer Works', title: 'Waste is just badly routed feedstock', description: 'Complete both recovery routes: turn Vinasse and CO2 into farm feed, then pyrolyse Bagasse into Charcoal, Wood Tar, and Wood Gas.', kind: 'optional', position: { x: 840, y: 320 }, icon: { type: 'resource', id: 'charcoal' }, prerequisites: ['fermentSugarWashQuest'], requirements: { recipes: [{ id: 'mix_fertilizer_liquor', amount: 1 }, { id: 'pyrolyse_bagasse', amount: 1 }] }, rewards: { scrip: 8 } },
]
